### ISSUE TITLE
(?) Fehler: Rückmeldung, Wörter mit Umlauten erzeugen eine Warnung und werden nicht geschrieben

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.cloud#10]
cloud.0	2017-02-16 20:12:47.828	warn	Unknown applianceId: H_ngeschrank

Smartname: Hängeschrank.

Erzeugt eine Warnung im Log und Ausgabe wird nicht in den Datenpunkt geschrieben.

**Comment by GermanBluefox** [comment]
Bist du sicher, dass du die Geräte mit Alexa Synchronisiert hast? Bitte Geräte Löschen und neu synchronisieren.

**Comment by ruhr70** [comment]
Es ist noch anders... sorry.

"Hängeschrank" war eine Alexa Gruppe innerhalb der Alexa App, die mittlerweile aber nicht mehr existiert? Bin mir nicht ganz sicher.

In der Alexa App taucht aber der Smartname "Hängeschrank" unter "meine Geräte" noch auf, mit der "Gruppe Hängeschrank". Aktuell Synchronisiert. Dort könnte ich dieses Gerät auch verwerfen.

Im Cloud Adapter taucht "Hängeschrank" nicht auf. Dort gibt es nur den Smartnamen "Küche Hängeschränke".


Kurz:

- in ioBroker gibt es "Hängeschrank" nciht
- "Alexa kennt Hängeschrank" und kann damit über ioBroker steuern

Ich habe das Gerät in der ioBroker App jetzt nicht verworfen, falls ich noch was nachschauen soll.
