### ISSUE TITLE
[Smartname] object Object

### ISSUE THREAD

**Issue by XneddyX** [ioBroker/ioBroker.cloud#102]
Moin.
Ich habe heute angefangen mich mit Aufzählung auseinander zu setzen, dabei ist mir aufgefallen, dass der Adapter die Smart Geräte nach folgendem Muster einträgt "[Smartname] object Object". Leider ist das nicht so schön wenn Alexa immer "Ich habe [Smartname] object Object auf......". Vielleicht kann das ja gefixt werden?
![1](https://user-images.githubusercontent.com/14812051/46312428-5465ff80-c5c5-11e8-9b08-c0b9533795eb.jpg)
![2](https://user-images.githubusercontent.com/14812051/46312489-7fe8ea00-c5c5-11e8-9054-e06741d60a5e.jpg)

Admin 3.5.10
Cloud 2.7.1

**Comment by Apollon77** [comment]
Welcher js-controller?

**Comment by XneddyX** [comment]
> Welcher js-controller?

1.4.2

**Comment by XneddyX** [comment]
Im übrigen besteht so ein ähnliches Problem auch im [Mobile Adapter](https://github.com/ioBroker/ioBroker.mobile)... Sollte ich das Problem da auch posten???

**Comment by chucky2002** [comment]
Habe seit neuestem das gleiche Problem. Bin dann dazu übergegangen bei Thermostaten die Geräte manuell im Cloud Adapter anzulegen. Bei Geräte über die HUE Schnittstelle benötige ich allerdings die smarte Aufzählung da darüber mehrere Werte zusammengefasst werden können.

**Comment by Steiger04** [comment]
Bei mir tritt der Effekt auch auf und zwar dann wenn ich die voreingestellten rooms und functions benutze. Sobald ich eigene anlege und diese dann benutze wird der Smartname richtig aufgelöst. Ich nutze js-controller v.1.4.2 und cloud v.2.6.2.

**Comment by adieball** [comment]
Bei mir tritt das auch mit eigenen auf, also eigentlich immer wenn Räume im Spiel sind
