### ISSUE TITLE
Datenpunkte lassen sich nicht mehr einfügen.

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.cloud#103]
Ich wähle einen eigenen Datenpunkt für die Aufnahme als Gerät .. und nichts passiert.
Ging aber alles vor kurzem noch.

**Comment by daniel-lo** [comment]
Ich bin auch nicht der Einzige (inkl. etwas mehr Infos):
https://forum.iobroker.net/viewtopic.php?f=20&t=17341

**Comment by Pascal51882** [comment]
https://forum.iobroker.net/viewtopic.php?f=20&t=12299&sid=200d8683c423b91de379a5a88e4e99ee&start=20
Beitrag auf Seite 2 war die Lösung :)

**Comment by daniel-lo** [comment]
Ein Unterstrich im Namen hat es bei mir getan. Ich schließe mal - obwohl es insgesamt nicht schön ist.

**Comment by GermanBluefox** [comment]
Es ist interessant wie willst du Unterstrich bei Alexa nennen?

daniel-lo <notifications@github.com> schrieb am Sa., 20. Okt. 2018, 06:47:

**Comment by GermanBluefox** [comment]
Ich will das Lösen. Mindestens irgendeine Fehlermeldung bringen.

Ich muss aber verstehen, was ich lösen muss.

**Comment by daniel-lo** [comment]
ich hab ein Datenpunkt erstellt der nescafe heißt. Sowohl ID und Name hießen dann nescafe. Kannst im Cloud-Adapter den Datenpunkt auswählen .. aber dann passiert nichts mehr. Hab direkt im Namensfeld ne_scafe draus gemacht und es funktionierte. Es gibt keinerlei Output zum Fehler.
Zum Problem steht auch ein wenig auf Deiner Seite ;-) ....
http://www.iobroker.net/docu/?page_id=5910&lang=de

**Comment by Apollon77** [comment]
ist es ggf das gleiche problem was letztens bei iot war das man datenpunkte im admin nicht/nur mit tabwechsel ändern konnte?!

**Comment by daniel-lo** [comment]
Tabwechsel hatte ich probiert .. hab aber damit nichts bewirken können.

**Comment by Baenker** [comment]
habe das selbe Problem. Habe unter Objekte "Systemvariablen" zwei neue States erstellt "Garagentor" und "Weihnachtsbeleuchtung". Beide sind boolean.

Mit einer älteren Version ging es. Habe auf der gleichen Ebene noch einen weiteren Punkt den ich bei Alexa nutze...

**Comment by IhorT** [comment]
Auch wenn es hier alt ist, wollte auch dazu schreiben. Habe schon so viele beiträge gelesen und nichts gefunden nur das hier hat mir geholfen:

**geht nicht:**

"smartName": {
  "de": "Garagentor"
  },

**Geht:**

"smartName": {
  "de": "Garagentor",
  "smartType": ""
},
