### ISSUE TITLE
Fehler "Gerät reagiert nicht" häuft sich in letzter zeit

### ISSUE THREAD

**Issue by Mazdaracer121** [ioBroker/ioBroker.cloud#104]
Befehle müssen teilweise 2 oder 3 mal abgesetzt werden damit die betreffenden Geräte schalten

**Comment by Apollon77** [comment]
Free oder pro Cloud Server?

**Comment by Apollon77** [comment]
Generell: In Arbeit: https://forum.iobroker.net/viewtopic.php?f=37&t=16882

**Comment by Baenker** [comment]
Kann das nicht geschlossen werden?

Die Gerätesteuerung über Alexa via Cloud-Adapter wurde ab 4.1.2020 eingestellt!

**Comment by Apollon77** [comment]
you're right. Thank you!
