### ISSUE TITLE
Feature-Wunsch: Bearbeiten von Smart-Geräten und -Gruppen sollte einfacher sein.

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.cloud#107]
Bisher muss ich einen Smart-Namen von Hand mehreren Geräten nacheinander zuordnen. Dabei ist unübersichtlich, welche Geräte schon verwendet sind, etc... Wünschenswert wäre die umgekehrte Richtung: Ich erstelle ein Smart-Gerät mit einem Namen und kann dann aus einer Liste mehrere Geräte auswählen. Vorschlag wäre etwa wie im folgenden Mockup:
![prasentation1](https://user-images.githubusercontent.com/17641229/47802842-791ed580-dd31-11e8-8f7c-6bf921838fc3.png)

In diesem Zuge könnte #99 ebenfalls gelöst werden.

**Comment by AlCalzone** [comment]
Bearbeiten der Geräte ist auch in 1.6.0 immer noch umständlich

**Comment by Apollon77** [comment]
Maybe solved in the future with Alias/Devices :-)

**Comment by AlCalzone** [comment]
Soll "Devices" auch Gruppen von Geräten ansteuern können? Wenn dem so ist, sollte man ggf. die Komplexität von hier dort hin auslagern. 
Nichtsdestotrotz ist die Menüführung in iot umständlich und mir graut es jedes Mal davor, wenn ich hier etwas ändern muss. Gruppen z.B. kann man gegenüber einzelnen "Geräten" auch nicht editieren.

**Comment by GermanBluefox** [comment]
Please move it to iot now. Cloud will not support devices from 01.03.2021
