### ISSUE TITLE
Feature request - Ausschluss von Smart Geräten für zweite Cloud Instanz

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.cloud#109]
Ziel wäre zwei Echo Dot mit zwei Amazon Konten in einem ioBroker zu nutzen, die Smart Geräte aber getrennt festlegen zu können. Zumindest einer Cloud Instanz bestimmte zu entziehen.

Ist-Zustand:
- separates Amazon Konto mit separaten Skills (u.a. dem ioBroker Skill)
- separate Alexa Instanz mit neuem ioBroker (net/pro) Cloud Login
- separate Cloud Instanz mit App Key des neuen ioBroker Kontos, welches dann mit dem ioBroker Skill des zweiten Amazon Kontos verknüpft wird

Aktuell sind aber alle Smart Geräte instanzübergreifend definiert durch den JSON Block (smartName) im Objekt/Datenpunkt.
Idee wäre dem JSON Knoten einen weiteren Key (black or whitelist) hinzuzufügen in dem man die cloud Instanz oder Echo Geräte IDs eintragen kann. Cloud Instanz Nummer wäre vllt. universeller als Echo Geräte IDs.

```
"smartName": {
  "de": "Lampe",
  "smartType": "LIGHT",
  "exclude": "cloud.1"
},
```

oder

```
"smartName": {
  "de": "Lampe",
  "smartType": "LIGHT",
  "exclude": "echo_device_id"
},
```

**Comment by Apollon77** [comment]
I personally would more like a whitelist rather a blacklist ... but in fact the same :-)

**Comment by Diginix** [comment]
Ist es überhaupt noch notwendig. Wenn ich mir den Aufbau der smart Geräte im JSON ansehe dann ist der Kontext zur Instanz-ID ja schon gegeben. D.h. wenn ich zusätzlich iot.1 hätte, dürfte das Gerät dort nich zu sehen sein.
"iot.0": {
  "smartName": {
    "de": "Lampe",
    "smartType": "LIGHT"
  }
}
