### ISSUE TITLE
Keine Verbindung mehr zur Cloud / Fehler beim anmelden

### ISSUE THREAD

**Issue by gitpaddex** [ioBroker/ioBroker.cloud#113]
Hallo an alle.

Ich habe nun schon seit ein paar Tagen das Problem, dass mein Cloud Adapter keine Verbindung aufbauen kann. Im Log steht nur "Cloud says: timeout".
Wenn ich versuche mich mit meinem Account auf https://iobroker.net/login oder https://iobroker.pro/login anzumelden kommt immer eine weiße Webseite mit "Unauthorized". Darunter einen schwarz gerahmte Box, die leer ist. Hier kann ich nichts machen.
Komisch finde ich nur, dass der Adapter trotz Fehler auf Grün springt. Ein nutzen von Alexa ist aber nicht möglich - alle Geräte werden als "offline" angezeigt.

Hat noch jemand das Problem?

Gruß
Paddex

**Comment by gitpaddex** [comment]
Danke für die schnelle Antwort. 
Was ich aber nicht verstehe: Ich nutze die Cloud nund schon über ein Jahr mit diesen Accountdaten. Dann habe ich den Adapter aktualisiert und damit wurde mein Pro Account gelöscht? Habe die gleichen Daten verwendet und mich neu angemeldet... klappt... OK, aber als ich den neuen AppKey eingefügt habe, sagt er mir jetzt im Log "Please buy remote access to use pro. If you did it, please wait 5 minutes". Hä? Bin verwirrt. Muss ich jetzt, obwohl ich ein Pro Account hatte, jetzt nochmal was kaufen um die Cloud weiter mit Alexa zu nutzen?

**Comment by Apollon77** [comment]
Hast du pro mit einer fernzugriffs Lizenz? Wenn nein dann ist genau das die erwartete Fehlermeldung. Ohne bezahlen nutzt man die Free Cloud bzw für alexa den iot adapter mit Limitierung. 

Wenn bei dir bisher pro ohne Lizenz funktioniert hat war das ein bug der gefixt ist. Es gab User die zB das kommuniziert und ausgenutzt haben.
