### ISSUE TITLE
Gleiche Geräte verhalten sich unterschiedlich

### ISSUE THREAD

**Issue by AkiraFFM** [ioBroker/ioBroker.cloud#115]
Hallo,

ich habe Datenpunkte für meine Digitalstrom Rolladenklemmen erstellt und diese über den Cloud Adapter für Alexa verfügbar gemacht. Die Geräte verhalten sich allerdings sehr unterschiedlich.

"Alexa, <Zimmername> Rolladen an" => Datenpunkt wird auf "true" gesetzt
"Alexa, <Zimmername> Rolladen aus" => Datenpunkt wird auf "false" gesetzt
Also alles gut.

Anders hingegen bei verwendung der Worte hochfahren / runterfahren:
"Alexa, <Zimmername> Rolladen hochfahren" =>  Datenpunkt für Wohnzimmer, Küche und Bad wird "true" gesetzt.
"Alexa, <Zimmername> Rolladen runterfahren" =>  Datenpunkt für Wohnzimmer, Küche und Bad wird "false" gesetzt.
Soweit sogut, aber jetzt wird es merkwürdig.
Im Arbeitszimmer und Schlafzimmer meldet Alexa bei "hochfahren / runterfahren" , dass dies von Geräte nicht unterstützt wird. Warum dies? Alles Datenpunkte sind gleich konfiguriert.
Es wird aber noch merkwürdiger.
Bei "Alexa, Kinderzimmer Rolladen runterfahren"  => Datenpunkt für Kinderzimmer wird auf "false" gesetzt. Paßt also.
Aber bei "Alexa, Kinderzimmer Rolladen hochfahren"  => Wird der Datenpunkt für Kinderzimmer ebenfalls  auf "false" anstatt auf "true" gesetzt.

Geräte wurden bereits sowohl in Alexa, alsauch die Datenpunkte gelöscht und neu angelegt.

**Comment by Baenker** [comment]
Kann das nicht geschlossen werden?

Die Gerätesteuerung über Alexa via Cloud-Adapter wurde ab 4.1.2020 eingestellt!

**Comment by Apollon77** [comment]
you're right. Thank you!
