### ISSUE TITLE
"unknown command: cmdStdout" & "unknown command: cmdExit"

### ISSUE THREAD

**Issue by xmace** [ioBroker/ioBroker.cloud#116]
During browsing trough iobroker via remote access (iobroker.pro) the log file is full of the following warn elements.

Bug or something wrong on my side?

> 
cloud.0 | 2019-01-18 14:29:48.423 | warn | Unknown command: cmdExit
-- | -- | -- | --
cloud.0 | 2019-01-18 14:29:47.239 | warn | Unknown command: cmdExit
cloud.0 | 2019-01-18 14:29:47.232 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:47.171 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:47.140 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:47.110 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:47.079 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:47.048 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:47.018 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:46.987 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:46.960 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:46.927 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:46.895 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:46.889 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:46.860 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:46.756 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:46.694 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:46.631 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:46.565 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:46.539 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:46.527 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:28.080 | warn | Unknown command: cmdExit
cloud.0 | 2019-01-18 14:29:26.943 | warn | Unknown command: cmdExit
cloud.0 | 2019-01-18 14:29:26.937 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:26.889 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:26.857 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:26.850 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:26.838 | warn | Unknown command: cmdStderr
cloud.0 | 2019-01-18 14:29:26.826 | warn | Unknown command: cmdStderr
cloud.0 | 2019-01-18 14:29:26.755 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:26.749 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:26.748 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:26.745 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:26.744 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:26.741 | warn | Unknown command: cmdStdout
cloud.0 | 2019-01-18 14:29:26.740 | warn | Unknown command: cmdStdout

**Comment by xmace** [comment]
still an issue in current version:
`

cloud.0 | 2019-02-22 07:39:13.168 | warn | Unknown command: cmdExit
-- | -- | -- | --
cloud.0 | 2019-02-22 07:39:12.166 | warn | Unknown command: cmdExit
cloud.0 | 2019-02-22 07:39:11.920 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:11.809 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:11.749 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:11.683 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:11.587 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:11.351 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:11.250 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:11.178 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:11.115 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:11.041 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:10.970 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:10.893 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:10.830 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:10.768 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:10.711 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:10.650 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:10.591 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:10.512 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:10.451 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:10.390 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:10.333 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:10.274 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:09.605 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:08.956 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:08.330 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:07.721 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:05.827 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:05.193 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:04.598 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:04.460 | warn | Unknown command: cmdExit
cloud.0 | 2019-02-22 07:39:03.408 | warn | Unknown command: cmdExit
cloud.0 | 2019-02-22 07:39:03.394 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:03.331 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:03.323 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:03.253 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:03.192 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:03.129 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:03.039 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:02.952 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:02.912 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:02.833 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:02.829 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:39:02.828 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:38:59.095 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:38:59.031 | warn | Unknown command: cmdStdout
cloud.0 | 2019-02-22 07:38:56.945 | warn | Unknown command: cmdStdout

`

**Comment by DirtyAtze** [comment]
I get the same warnings. I mover ioBroker from Rpi3 to Rpi4 by restoring a minimal Backup.
Is there any Soluton yet?

**Comment by martinschm** [comment]
Same here:

cloud.0 | 2019-07-23 15:46:11.081 | info | User accessed from cloud
-- | -- | -- | --
cloud.0 | 2019-07-23 15:44:43.981 | warn | Unknown command: cmdExit
cloud.0 | 2019-07-23 15:44:42.980 | warn | Unknown command: cmdExit
cloud.0 | 2019-07-23 15:44:42.965 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:44:42.897 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:44:42.787 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:44:42.738 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:44:42.683 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:44:42.644 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:44:42.286 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:44:42.285 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:44:42.283 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:44:30.308 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:44:29.148 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:44:29.146 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:44:25.148 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:44:24.855 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:44:20.998 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:44:16.503 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:44:10.744 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:44:10.682 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:44:10.605 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:44:10.601 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:44:10.600 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:42:56.390 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:42:55.431 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:42:54.410 | warn | Unknown command: cmdStdout
cloud.0 | 2019-07-23 15:42:54.146 | warn | Unknown command: cmdStdout
