### ISSUE TITLE
Cloud adapter apparently turned yellow since days

### ISSUE THREAD

**Issue by SayAndre** [ioBroker/ioBroker.cloud#117]
I can't find any help on forums so I try here.
Since 2 weeks one of my 2 cloud instances just stays yellow. Even after upgrading it to pro.
Key is enterend, web instance is working. I don't know what's wrong.
I reinstalled / regenerated the API keys and so on. in the log it just said "Timeout" Connection Lost.
The second cloud instance is just running without any issues.
Attached my debug log, after just restarting it. Looks OK? But stays yellow and nothing cloud related is working.

[Debug_Log.txt](https://github.com/ioBroker/ioBroker.cloud/files/2777041/Debug_Log.txt)

**Comment by Apollon77** [comment]
And when you try to delete this one instance that is always yellow and recreate it?

**Comment by Apollon77** [comment]
Log shows that cloud adapter is successfully connected ... is only admin showing yellow?
What is shown when you go to Objects -> cloud.2.info.connection What is the status there? if it is true then only admin is displaying wrong

**Comment by SayAndre** [comment]
> And when you try to delete this one instance that is always yellow and recreate it?

I just did that's why it is now called cloud.2 instead of cloud.0 >.< Can I rename that?

> Log shows that cloud adapter is successfully connected ... is only admin showing yellow?
> What is shown when you go to Objects -> cloud.2.info.connection What is the status there? if it is true then only admin is displaying wrong

![unbenannt](https://user-images.githubusercontent.com/46874191/51469050-a8f9da00-1d70-11e9-998d-cb17cee00351.PNG)

**Comment by Apollon77** [comment]
very strange. in fact the log schows that the adapter is cuccessfully connected. We need to check deeper

**Comment by SayAndre** [comment]
If everything would work fine I wouldnt care. But everything cloud related is Not working as well. Im considering reinstalling my Pi fully. Is there a way to make a full backup of the iobroker?

**Comment by Apollon77** [comment]
What is shown when you login on cloud webpage with both accounts. it should appear a list of the available remote access adapters. or do you get error messages saying it is not connected? WHat exactly is not working? maybe switch to Forum again to discuss this? :-)

**Comment by SayAndre** [comment]
Login into cloud webpage with both accounts also fine. Pro & Free.
All smart devices added in the cloud are not working.
Like starting my computer via WOL / Powering on my TV / Stereo via Broadlink or controlling my heaters over dect with alexa.
I don't mind switching to the forum, but I don't wanna double post so I switched over here :-)
