### ISSUE TITLE
Cloud says: timeout

### ISSUE THREAD

**Issue by DavidTielke** [ioBroker/ioBroker.cloud#119]
Hallo,

Erstmal: Grandiose Arbeit die Ihr da jeden Tag verrichtet, Ihr macht einen fabelhaften Job!

Zu meinem Problem: ich habe den Cloud-Adapter seit über einem Jahr im Einsatz ihn aber nicht besonders oft benutzt, weil die Verbindung immer mal wieder verloren ging. Trotzdem konnte ich bei einer laufenden Verbindung meine Geräte steuern.

Heute habe ich bemerkt, dass der Adapter auf rot stand, sich also selbst beendet hat. Bei einer Reaktivierung springt der Adapter immer wieder auf "gelb" mit dem Log-Hinweis auf einen Timeout:

cloud.0 | 2019-02-21 11:20:46.998 | info | Connection changed: io client disconnect
cloud.0 | 2019-02-21 11:20:46.998 | info | Adapter redirected temporally to "https://iobroker.net:10560" in one minute. Reason: command from server
cloud.0 | 2019-02-21 11:20:46.826 | info | Trying to connect as system.user.admin
cloud.0 | 2019-02-21 11:19:53.150 | info | Connection changed: io server disconnect
cloud.0 | 2019-02-21 11:19:52.149 | error | Cloud says: timeout
cloud.0 | 2019-02-21 11:19:47.901 | info | Trying to connect as system.user.admin
cloud.0 | 2019-02-21 11:19:46.792 | info | Connecting with https://iobroker.net:10555 with "hier_war_mal_ein_key"
cloud.0 | 2019-02-21 11:19:46.702 | info | starting. Version 2.6.2 in /opt/iobroker/node_modules/iobroker.cloud, node: v8.7.0

Ich habe jetzt seit einer Stunde alles mögliche probiert:
- Instanzen entfernen
- Adapter löschen und neu installieren
- Key neu setzen
- neuen Key generieren lassen

Ab und zu habe ich eine Verbindung:

cloud.0 | 2019-02-21 11:21:47.178 | info | Connection changed: connect
-- | -- | -- | --
cloud.0 | 2019-02-21 11:21:47.012 | info | Trying to connect as system.user.admin

Aber wenn ich dann neu connecte, klappt der nächste Verbindungsversuch erst nach ca. 15 Minuten.

Selbst wenn ich eine Verbindung bekomme, kann ich mit Alexa meine Geräte nicht erreichen "David Büro Lichte konnte nicht erreicht werden". Eine vergleichbare Fehlermeldung bekomme ich auch in der Alexa-App.

Liegt es an meinem Adapter? Ist der Server überlastet?

Danke für Eure Mühen!

**Comment by Apollon77** [comment]
Wenn du eine Verbindung hast lass sie. Warum solltest du dann den Adapter neu verbinden. Ja ggf sind hier Sicherheitsmechanismen drin. 

Bitte den skill in Alexa deaktivieren und neu verknüpfen. Dann Geräte neu suchen. Tut es dann wieder?
