### ISSUE TITLE
Cloud Adapter verbindet nicht

### ISSUE THREAD

**Issue by bjwelker** [ioBroker/ioBroker.cloud#12]
Nachdem ich das Problem schonmal hatte ist es jetzt wieder so das der Cloud Adapter hochfährt usw. er aber nicht auf grün geht und man über iobroker.net auch nicht die Applications sieht. Vom iobroker kann ich iobroker.net pingen das kann es auch nicht sein. Hast du da evtl eine Idee wieso er sich absolut nicht verbinden will?

**Comment by GermanBluefox** [comment]
Bitte dein Login an "dogafox at gmail.com" mit Beschreibung senden. Ich
werde checken.

2017-03-01 16:49 GMT+01:00 Bjoern <notifications@github.com>:

**Comment by GermanBluefox** [comment]
Can I close it?
