### ISSUE TITLE
Farbe für hue kompatible Glühlampe

### ISSUE THREAD

**Issue by prankousky** [ioBroker/ioBroker.cloud#122]
Hallo,

ich versuche gerade, eine `Philips Hue` kompatible Glühlampe (Marke `innr`) über den Cloud Adapter zu steuern. Sie ist mit ioBroker über den `zigbee` Adapter verbunden und ich kann sie auch steuern.

Ich war davon ausgegangen, dass das Einstellen der Farbe gar nicht möglich sei, bzw. nur, wenn Alexa auf Englisch gestellt ist (steht so auf der Startpage, wenn ich das nicht falsch interpretiert habe). Auf der Suche in den Issues hier habe ich aber gesehen, dass anscheinend einige doch auf Deutsch ihre Farbwerte steuern können (in der betroffenen Issue wollte jemand auf "weiß" schalten, es wurde aber immer "rot" geschaltet; von englischer Sprache wurde nichts erwähnt).

Also, kann ich die Lampe farblich über den Cloud Adapter steuern? Die Lampe hat die auf dem Bild zu sehenden Einstellungsmöglichkeiten (Bild lässt sich anklicken und vergrößern)

![screenshot](https://i.imgur.com/UFjBCAj.png)

Ich habe deaktiviert, dass der Cloud Adapter  automatisch alle Objekte findet, und wollte diese Lampe manuell hinzufügen. Das Ein-/Ausschalten ist zeitgesteuert und/oder wird manuell über das Smartphone erledigt. Hierfür habe ich also keinen Alexa Befehl eingerichtet. Aber ich würde gerne die Farbe über Alexa umstellen können. Geht das?

Alternativfrage: ist es irgendwie möglich, über den Cloud den letzten Befehl einfach als Text auszugeben? Beispiel **Befehl**: `Alexa, Flurlicht Farbe Blau`, **Ausgabe** `Flurlicht Farbe Blau` o.Ä.? So könnte man das ja selbst parsen, indem man mit Regex das betroffene Gerät (`Flurlicht`) und die gewünschte Farbe (`Blau`) ausliest und mit diesen Werten weiter arbeitet.

Sorry, falls das jetzt etwas naiv gefragt ist. Auch wenn ich den ioBroker schon eine Weile nutze, bin ich immer noch eher Anfänger, was das Thema angeht. Hauptsächlich arbeite ich mit node-red, was aber in manchen Dingen (`Cloud` Adapter, `zigbee` Adapter) einfach nicht mit dem ioBroker mithalten kann.

Vielen Dank im Voraus für Eure Ideen und Tipps :)

**Comment by Apollon77** [comment]
AN sich sollte ein State mit ROlle level.color.rgb steuerbar sein - zumindestens geht das bei mir. Der Wert der reingeschrieben wird ist aber #rrggbb ... in deinem Screenshot fehlt das # ... ggf ist das das problem? ggf braucht es da noch einen Fix bei zigbee?

**Comment by prankousky** [comment]
Vielen Dank für die Info @Apollon77 
Ich habe jetzt ein Testobjekt angelegt, welches keinen Wert hatte; dies wurde vom Cloud Adapter für Color erkannt. Dem Output habe ich dann einfach das `#`entfernt und ihn an das entsprechende Objekt der Glühlampe weitergeleitet.

Aber: weiß der Cloud Adapter denn **vorher**, welche Werte das Objekt annimmt? Ich schaffe es leider erst nächste Woche zu testen, aber ich könnte ja den Wert des Objektes der Glühlampe einmal auf " "  (also leer) stellen und ihn dann versuchen, ihn mit dem Cloud Adapter zu verbinden. 
(oder anders: ob der zigbee Adapter nun `#FFFFFF` als Wert akzeptiert, sollte doch dem Cloud Adapter egal sein und er müsste den Wert einfach trotzdem übermitteln können..?)

**Comment by madjack84** [comment]
![Screenshot_20190609-144007](https://user-images.githubusercontent.com/24653087/59159093-f16a2800-8ac4-11e9-9f16-b4b2b4e7e1a6.png)
Inzwischen ist Deutsch laut developer Portal verfügbar. Am besten die Beschreibung ändern. :)

**Comment by Baenker** [comment]
Hat das Problem sich nicht erledigt?

Die Gerätesteuerung über Alexa via Cloud-Adapter wurde ab 4.1.2020 eingestellt!

**Comment by Apollon77** [comment]
you're right. Thank you!
