### ISSUE TITLE
states werden bei Änderung nicht aktualisiert

### ISSUE THREAD

**Issue by chefkoch009** [ioBroker/ioBroker.cloud#128]
Szenario 1: Vis lokal: wird ein state (z.B. eine Lampe angeschalten) funktioniert. Wird die gleiche Lampe über Lichtschalter ausgeschaltet wird Änderung in Vis angezeigt. Also OK.

Szenario 2: Vis via cloud pro: anschalten der Lampe über vis funktioniert, state wird korrekt angezeigt. Schalten der gleichen Lampe über Lichtschalter => vis wird NICHT aktualisiert. Nach neuanmeldung bei cloud pro werden die momentanen Zustände richtig angezeigt, aber nicht die die sich (solange die cloud verbindung besteht) ändern.

**Comment by Apollon77** [comment]
Ist sichergestellt das nur ein Browser zu einem Zeitpunkt eine Cloud Verbindung hat? Mehrere parallele Cloud Verbindungen sind nicht möglich. Die letzte Verbindung gewinnt und das hat dann den Effekt das alle früheren Verbindungen keine aktuellen Daten mehr bekommen. Kann es sein das irgendwo noch Verbindungen sind oder herkommen via Cloud?

**Comment by chefkoch009** [comment]
Das ist definitiv sichergestellt. Kein anderer Tab, kein anderer Browser. (kontrolliert auf allen Tablets, Laptops und Handys).

**Comment by nevermind2001** [comment]
Ich würde mich wirklich freuen, wenn sich mal jemand des Problems annehmen würde. Hier habe ich den Sachverhalt bei mir nochmals genau geschildert:

https://forum.iobroker.net/topic/24167/vis-keine-aktualisierung-%C3%BCber-cloud

**Comment by Omega236** [comment]
Habe das gleiche Problem, habe schon viel ausprobiert.
Habe auch schon extra Web Adapter für Cloud erstellt, hier alles mögliche ausprobiert, aber ich bekomme Änderungen wenn ich über Pro verbunden bin nicht mit. 
Hoffentlich hat hier jemand ne Lösung.
Das Problem besteht seit min. Februar 2019.
Bin vor kurzem auf einen neuen Host umgestiegen (mit Backup und dann Restore) der Fehler ist mitgewandert.

**Comment by algar42** [comment]
Confirm. No updates of values over cloud after page accessed and closed one time. Then nothing helps - you can close browser, sign out and sign in to cloud.... only restart of cloud adapter helps.

**Comment by algar42** [comment]
Was the issue been investigated? Very annoyng that it does not work even with payed licence.

**Comment by Apollon77** [comment]
So I currently do a test ... I come back here with the results too

**Comment by algar42** [comment]
Also spotted that Cloud adapter stops working (becomes red) after some time without any log messages. When I restart adapter the log looks like:
![image](https://user-images.githubusercontent.com/40002726/65528798-b7028a80-defd-11e9-894e-b7b154965801.png)

It seem to me that adapter don't see broken connection and not reconnect automatically. 

Maybe this is also related to the topic of this issue??

**Comment by Apollon77** [comment]
normally cloud reconnects after a certain (with random timeframe parts to streamline load after cloud restarts) timeframe

**Comment by Omega236** [comment]
Gefühlt wird es immer schlimmer.
Vis ist mitlerweile über cloud garnicht mehr verwendbar, sobald man irgendetwas in VIS anklickt scheint die Verbingung verloren zu gehen. Echt Schade weil man so niemandem mehr zeigen kann wie toll IoBroker ist :(

ab User disconnected from cloud scheint es nicht mehr zu funktionieren. würde gern helfen den Fehler zu finden, weiß aber garnicht wo ich anfangen soll zu suchen.

`

cloud.0 | 2019-10-10 15:24:45.382 | info | User accessed from cloud
-- | -- | -- | --
cloud.0 | 2019-10-10 15:24:45.382 | info | User accessed from cloud
cloud.0 | 2019-10-10 15:24:45.332 | info | User accessed from cloud
cloud.0 | 2019-10-10 15:24:45.332 | info | User accessed from cloud
cloud.0 | 2019-10-10 15:24:45.015 | info | User disconnected from cloud
cloud.0 | 2019-10-10 15:24:38.029 | debug | socket NUlDkMEKYYbkq8oZDvS9 changed socket name from vis.0 to flot
cloud.0 | 2019-10-10 15:24:37.982 | info | User accessed from cloud
cloud.0 | 2019-10-10 15:24:37.878 | info | User accessed from cloud
cloud.0 | 2019-10-10 15:24:37.827 | info | User accessed from cloud
cloud.0 | 2019-10-10 15:24:37.827 | info | User accessed from cloud
cloud.0 | 2019-10-10 15:24:36.281 | debug | Subscribes:  *, vis.0.control.instance, vis.0.control.data, vis.0.control.command,  hm-rpc.0.CUX9001001.1.STATE, hm-rpc.1.NEQ0532306.1.LOWBAT,  hm-rpc.1.NEQ0532306.1.TEMPERATURE, hm-rpc.1.NEQ0532306.2.TE
cloud.0 | 2019-10-10 15:24:35.544 | debug | Subscribes:  *, vis.0.control.instance, vis.0.control.data, vis.0.control.command,  hm-rpc.0.CUX9001001.1.STATE, hm-rpc.1.NEQ0532306.1.LOWBAT,  hm-rpc.1.NEQ0532306.1.TEMPERATURE, hm-rpc.1.NEQ0532306.2.TE
cloud.0 | 2019-10-10 15:24:31.194 | debug | Subscribes:  *, vis.0.control.instance, vis.0.control.data, vis.0.control.command,  hm-rpc.0.CUX9001001.1.STATE, hm-rpc.1.NEQ0532306.1.LOWBAT,  hm-rpc.1.NEQ0532306.1.TEMPERATURE, hm-rpc.1.NEQ0532306.2.TE
cloud.0 | 2019-10-10 15:24:30.105 | debug | 2019-10-10T13:24:30.104Z Request authenticate [system.user.admin]

`

**Comment by Omega236** [comment]
Ich habe nun eine neue Cloud.1 Instanz erstellt und einen neuen Account unter iobroker.net erstellt und diesen verwendet.

Damit funktioniert VIS ohne Probleme!!!
Das Problem liegt also wohl am PRO oder am IOT-Adater (der auch meinen PRO-Account nutzt)

**Comment by Apollon77** [comment]
Der Grund ist inzwischen bekannt, der Fix nur nicht ganz so simpel, wi bereits auch einmal im Forum schon geschrieben. Wir sind aber dran!

**Comment by Apollon77** [comment]
Please use cloud adapter 2.8.0 ... fixed with this and the server update yesterday night. Please verify and comment here!!

**Comment by chefkoch009** [comment]
Function is verified. Now it works. The  states now where submitted correclty in the way I mentioned in bug-opening-statement.

Thanks
