### ISSUE TITLE
Smart device object with id length over 1024 can not be deleted

### ISSUE THREAD

**Issue by hieblmedia** [ioBroker/ioBroker.cloud#13]
Object with id length over 1024 can not be deleted in smart devices.

In the Broadlink Adapter we have very long codes. In this case i found this problem.

In ioBroker ids greater then 1024 length are supported. But in the cloud configuration the id is cutted of and not deletable.

Here an example:
`broadlink.3.IR_Signals.broadlink.3.IR_Signals.190c1a0c0c1a190c190d0c19190d190c190d0c190d19190c0d190c190d19190d0c19190c0d190c190d19190c0d19190d190c190c190d190c1a0c0d190c19190d180d0d180d19190d190c190d0c19190d190c190d0c0002010c0d0c0d0c0d0c0d0c0d0c0d0c0d0c0d0c0d0c0d0c0d0c7d0d19190c0d19190d180d190d0c190c190d19190c0d190c1a180d0c1a0c190d19180d190c1a0c190d190c0d190c19190d190c0d19190c190d0c19190d190c190d0c190d19190d0c190c1a0c19190c0d19190d0c190d190c19190c0d19190d180d190c190d190d180d0d190c19190d190c0d190c19190d190c190d0c1a180d190c190d0c0002010d0c0c0d0c0d0c0d0c0d0c0d0c0d0d0c0d0c0c0d0c0d0c7e0c19190d0c19190d180d190d0c190c1a0c19190d0c190d19190c0c190d190d19180d190d190c190c1a0c0d190c19190d190c0d19190c190d0c19190d190c190d0c190d19190c0d190c1a0c19190c0d19190c0d190c1a0c19190d0c19190c190d190c190d190d190c0d190c19190d190c0d190c19190c1a0c190d0c19190d190d180d0c0002010c0d0c0d0c0d0c0d0c0d0c0d0c0d0d0c0c0d0c0d0c0d0c7d0d19190c0d19190c1a0c190c0d190d180d19190d0c190d19180d0c1a0c190d181a0c190d190c190d190c0d190c19190d190c0d19190c190d0c19190d190c190d0c190d19190d0c190c190d19190d0c19190d0c190c190d19190d0c19190d180d190c1a0c190d190c0d190c19190d190c0d190c1a190d1a0d1a0d0d1b1a0d1b0e0d1c0d0005dc180d`

**Comment by GermanBluefox** [comment]
I think the problem was solved in broadlink ?
