### ISSUE TITLE
Save buttons are always greyed out

### ISSUE THREAD

**Issue by derrapf** [ioBroker/ioBroker.cloud#130]
Even if ou change any thing in cloud (for example editing or deleting devices)  the save buttons are still greyed out.
![grafik](https://user-images.githubusercontent.com/11745094/63118648-92320380-bf9e-11e9-85c3-66c8e3fdc364.png)

**Comment by mabeca96** [comment]
i have the same Problem

**Comment by Baenker** [comment]
kann doch geschlossen werden oder?

Die Gerätesteuerung über Alexa via Cloud-Adapter wurde ab 4.1.2020 eingestellt!

**Comment by Apollon77** [comment]
you're right. Thank you!

**Comment by derrapf** [comment]
Same Problem occurs on IOT
For example when I change Smart Name.
Save Buttons are always greyed out.

**Comment by Apollon77** [comment]
Then please create on iot adapter.
