### ISSUE TITLE
Iobroker.net ssl certificate expired

### ISSUE THREAD

**Issue by t0mcat1337** [ioBroker/ioBroker.cloud#131]
Hi all,

Since today it's not possible to control iobroker devices with Alexa iobroker skill.
Visiting https://iobroker.net I realized, that the SSL cert is expired. Could be the problem imho ;)

**Comment by wossix** [comment]
same issue here. ;)

**Comment by Apollon77** [comment]
certificate updated. sorry

**Comment by captchaos99** [comment]
Thank U for fast fixing :)
