### ISSUE TITLE
uncaught exception --> connection lost

### ISSUE THREAD

**Issue by blackeagle998** [ioBroker/ioBroker.cloud#135]
Hello,

system: Raspberry PI 4
js-controller 2.2.7
cloud adapter 3.0.1
node 10.18.1
nodejs 10.18.1
npm 6.12.0

When I am using the pro account connection via cloud adapter I get error messages nearly every 2 - 3 minutes and then the connection is lost:

`

cloud.0 | 2020-01-22 15:10:11.120 | error | at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
-- | -- | -- | --
cloud.0 | 2020-01-22 15:10:11.120 | error | at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
cloud.0 | 2020-01-22 15:10:11.120 | error | at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
cloud.0 | 2020-01-22 15:10:11.120 | error | at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
cloud.0 | 2020-01-22 15:10:11.120 | error | at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
cloud.0 | 2020-01-22 15:10:11.120 | error | at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
cloud.0 | 2020-01-22 15:10:11.120 | error | at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:228:12)
cloud.0 | 2020-01-22 15:10:11.120 | error | at Socket.onevent (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:270:10)
cloud.0 | 2020-01-22 15:10:11.120 | error | at Socket.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
cloud.0 | 2020-01-22 15:10:11.120 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.cloud/lib/socket.js:1587:44)
cloud.0 | 2020-01-22 15:10:11.120 | error | (21302) TypeError: Cannot read property 'k5EzsXYiQ6jKZcFnAhE0' of undefined
cloud.0 | 2020-01-22 15:10:11.119 | error | (21302) uncaught exception: Cannot read property 'k5EzsXYiQ6jKZcFnAhE0' of undefined

`

`

host.raspberrypi | 2020-01-22 15:10:12.223 | error | Caught by controller[0]: at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
-- | -- | -- | --
host.raspberrypi | 2020-01-22 15:10:12.223 | error | Caught by controller[0]: at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
host.raspberrypi | 2020-01-22 15:10:12.223 | error | Caught by controller[0]: at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
host.raspberrypi | 2020-01-22 15:10:12.223 | error | Caught by controller[0]: at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
host.raspberrypi | 2020-01-22 15:10:12.222 | error | Caught by controller[0]: at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
host.raspberrypi | 2020-01-22 15:10:12.221 | error | Caught by controller[0]: at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
host.raspberrypi | 2020-01-22 15:10:12.221 | error | Caught by controller[0]: at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:228:12)
host.raspberrypi | 2020-01-22 15:10:12.221 | error | Caught by controller[0]: at Socket.onevent (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:270:10)
host.raspberrypi | 2020-01-22 15:10:12.220 | error | Caught by controller[0]: at Socket.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
host.raspberrypi | 2020-01-22 15:10:12.220 | error | Caught by controller[0]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.cloud/lib/socket.js:1587:44)
host.raspberrypi | 2020-01-22 15:10:12.219 | error | Caught by controller[0]: TypeError: Cannot read property 'k5EzsXYiQ6jKZcFnAhE0' of undefined

`

Can anyone please have a look at this and tell me what to do?

Thank you in advance!

**Comment by Baenker** [comment]
habe das gleiche Problem

**Comment by Apollon77** [comment]
Please try 1.3.2 from GitHub

**Comment by blackeagle998** [comment]
> Please try 1.3.2 from GitHub

Hallo Apollon,

ich habe den Cloud Adapter per Github aktualisiert, habe aber jetzt Version 3.0.2 das passt irgendwie nicht zu deiner genannten Version 1.3.2?!
Hab ich das richtige installiert?

![image](https://user-images.githubusercontent.com/58532773/74413970-bcc32300-4e40-11ea-80f0-6d91b5007756.png)

**Comment by Apollon77** [comment]
Yes was a typo ... 3.0.2 :-)

**Comment by blackeagle998** [comment]
> Please try 1.3.2 from GitHub

Läuft seit 3 Stunden problemlos, bisher nicht einen Abbruch.
Herzlichen Dank!!!
