### ISSUE TITLE
requireLog is not supported by this adapter! Please set common.logTransporter to true

### ISSUE THREAD

**Issue by Baenker** [ioBroker/ioBroker.cloud#136]
im Log erscheint ab und zu folgende Meldung

`

cloud.0 | 2020-01-27 06:42:02.273 | warn | (3074) requireLog is not supported by this adapter! Please set common.logTransporter to true
-- | -- | -- | --

`

js-controller 2.1.1 Node 10.18.1 cloud 2.80.

Fehler tritt erst seit Update auf js-controller 2.1.1 auf.

**Comment by Apollon77** [comment]
should be fixed on GitHub 1.3.2 from now on :-)

**Comment by Apollon77** [comment]
I meaned 3.0.2

**Comment by FlexerJR** [comment]
Hallo @Apollon77 Habe heute diese Meldung im Log gefunden nach dem Update von gestern.

Ist das nicht schon gefixt?



<html>
<body>


web.0 | 2022-05-20 07:40:27.572 | warn | requireLog is not supported by this adapter! Please set common.logTransporter to true
-- | -- | -- | --



</body>
</html>

**Comment by Apollon77** [comment]
Neues issue bitte öffnen
