### ISSUE TITLE
Received unknown command: log

### ISSUE THREAD

**Issue by armintan** [ioBroker/ioBroker.cloud#137]
I'm using the cloud adapter with an iobroker.pro application key. Whenever I load e.g vis via iobroker.pro (which works), I get tons of logs on the iobroker host wich says: 
error - Received unknown command: log

**Comment by Marty56** [comment]
I am having the bug as well. It seems to be browser related.
Safari both desktop and IOS Version seem to be affected.
Using Chrome shows no error.

**Comment by Marty56** [comment]
Mit dem Update der iobroker App auf iPhone funktioniert seit neustem der Aufruf der VIS Oberfläche überhaupt nicht mehr und das Log ist voll mit den Fehlermeldungen

**Comment by splizz1st** [comment]
I had the same problem with the iobroker ios app. After many attempts, I deleted the app and, from my point of view, reinstalled it with the same settings. Everything works now.
