### ISSUE TITLE
Just stopped running on 25th April

### ISSUE THREAD

**Issue by Moormerlander** [ioBroker/ioBroker.cloud#14]
The cloud adapter just stopped working last night. Several restarts of the adapter and the Raspberry Pi had no effect. I have no clue what to do now.

**Comment by Apollon77** [comment]
fixed

**Comment by Moormerlander** [comment]
thx!

May i ask you about the reason?

**Comment by Apollon77** [comment]
iobroker.net server went down and needed to be manually restarted :-(

**Comment by Apollon77** [comment]
see http://forum.iobroker.net/viewtopic.php?p=64046#p64046
