### ISSUE TITLE
Add IoBroker.LoveLace to cloud server

### ISSUE THREAD

**Issue by algar42** [ioBroker/ioBroker.cloud#140]
Is it possible to make Lovelace frontend available from cloud? 
See https://github.com/ioBroker/ioBroker.lovelace/issues/87#issuecomment-639103461

**Comment by Garfonso** [comment]
No, this should still happen. 😄 
Not sure what needs to be done for it to happen, though?

**Comment by algar42** [comment]
This seems to be added now. But I get '404 remote answer' message when trying to connect from cloud. Is it because lovelace is using port 8091 by default? what should be done to connect?

**Comment by Garfonso** [comment]
You need to select the right lovelace instance in cloud-Options. At least that is what was wrong when I got the 404 error.

**Comment by algar42** [comment]
ah.. thanks :) Missed that option

**Comment by ahilwers** [comment]
I selected my Lovelace instance in the settings of the Cloud adapter but if I open https://iobroker.pro/lovelace/ I only see a black empty screen with an empty grey bar at the top. I don't get any error messages or entries in the logs. If I open Lovelace locally everything works fine. Is there something else that needs to be configured here?

**Comment by algar42** [comment]
Same for me

**Comment by GermanBluefox** [comment]
The functionality is not yet deployed on server. Just test went OK.
