### ISSUE TITLE
	(1503) Received unknown command: log

### ISSUE THREAD

**Issue by pegemultra** [ioBroker/ioBroker.cloud#141]
The log shows a lot off errors:
(1503) Received unknown command: log

The vis App dosn't show the inventwo Widget. Browser works well. In use vis App log 1503
--

**Comment by Apollon77** [comment]
Yes This is a very new adapter and needs to be integrated into cloud ...

**Comment by Marty56** [comment]
This bug ist still not resolved.
Each time I log in remotely using Safari both on macOS, iPadOS or iOS I getting a lot of these error messages.

**Comment by GermanBluefox** [comment]
This must be fixed now (App 2.2.0 + cloud 4.0.7)
