### ISSUE TITLE
Received unknown command: log when accessing vis via remote login and pro account 

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.cloud#144]
Using iobroker pro remote access vis Safari (V 14) and access to the webui of vis I am receiving about 60 error messages in the log file.
Same behavior when using iPadOS oder iOS.
Cloud Adapter ist Version 3.0.4.
`

cloud.0 | 2020-10-14 04:42:30.456 | error | (3550) Received unknown command: log
-- | -- | -- | --
cloud.0 | 2020-10-14 04:42:30.454 | error | (3550) Received unknown command: log
cloud.0 | 2020-10-14 04:42:30.453 | error | (3550) Received unknown command: log
cloud.0 | 2020-10-14 04:42:30.453 | error | (3550) Received unknown command: log
...

`

**Comment by Marty56** [comment]
Update: The error logs are also appearing using chrome.

**Comment by Marty56** [comment]
Update: Using a non pro account is working without errors in the log file

**Comment by GermanBluefox** [comment]
Fixed in 4.0.6
