### ISSUE TITLE
Nach Update auf 4.0.1 Fehler im Errorlog

### ISSUE THREAD

**Issue by MarkSau** [ioBroker/ioBroker.cloud#161]
Nach dem Update auf 4.0.1 kommen folgende Fehlermeldungen:

`

cloud.0 | 2021-01-18 08:00:54.558 | error | (30760) Cannot activate admin.0 for cloud, because authentication is enabled. Please create extra instance for cloud
-- | -- | -- | --
cloud.0 | 2021-01-18 08:00:54.556 | error | (30760) Cannot activate web.0 for cloud, because authentication is enabled. Please create extra instance for cloud

`
Mit 4.0.0 kommen die Meldungen nicht.
Was muss ich den machen bzw. einstellen?

**Comment by Apollon77** [comment]
naja, sind die meldungen korrekt? Wenn ja ist doch gut das die meldungen jetzt kommen weil es würde sonst einfach nicht gehen
