### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dragon0501** [ioBroker/ioBroker.cloud#162]
New Error code in Log. Broker is offline

`

cloud.0 | 2021-01-26 09:05:44.185 | error | (29828) Error: Cannot parse answer from server: SyntaxError: Unexpected token < in JSON at position 0
-- | -- | -- | --

`
Adapterversion: 4.0.2
![Screenshot 2021-01-26 at 09 09 31](https://user-images.githubusercontent.com/59663011/105817760-53d3ad00-5fb6-11eb-8198-e8ccace7cf8a.png)

If you use login:

`

cloud.0 | 2021-01-26 09:13:38.405 | warn | (30249) Terminated (-100): Without reason
-- | -- | -- | --
cloud.0 | 2021-01-26 09:13:28.402 | info | (30249) Connection lost
cloud.0 | 2021-01-26 09:13:28.402 | info | (30249) Connection changed: io client disconnect
cloud.0 | 2021-01-26 09:13:28.399 | info | (30249) Adapter redirected temporally to "https://iobroker.pro:10556" in one minute. Reason: command from server
cloud.0 | 2021-01-26 09:13:28.374 | info | (30249) Connection changed: connect
cloud.0 | 2021-01-26 09:13:28.258 | info | (30249) Trying to connect as system.user.admin
cloud.0 | 2021-01-26 09:13:28.149 | info | (30249) Connecting with https://iobroker.pro:10555 with XXX
cloud.0 | 2021-01-26 09:13:27.727 | info | (30249) starting. Version 4.0.2 in /opt/iobroker/node_modules/iobroker.cloud, node: v12.20.1, js-controller: 3.2.11
-- | -- | -- | --

`

**Comment by Apollon77** [comment]
Ja, aktuell Wartungsarbeten. sorry
