### ISSUE TITLE
on  4.0.6 Pro Server not configurable

### ISSUE THREAD

**Issue by spoeh-man** [ioBroker/ioBroker.cloud#165]
**Describe the bug**  
After Update to 4.0.6 Cloud Stops with the errors

host.IoBroker | 2021-01-30 07:44:43.298 | info | "system.adapter.cloud.0" disabled
-- | -- | -- | --
cloud.0 | 2021-01-30 07:44:39.193 | info | (27390) Connection lost
cloud.0 | 2021-01-30 07:44:39.192 | info | (27390) Connection changed: io server disconnect
cloud.0 | 2021-01-30 07:44:38.192 | error | (27390) Cloud says: Pro key for .net cloud
cloud.0 | 2021-01-30 07:44:38.189 | warn | (27390) Adapter stopped. Reason: Pro key for .net cloud. Please change URL in config to https://iobroker.pro:10555
cloud.0 | 2021-01-30 07:44:38.141 | info | (27390) Connection changed: connect
cloud.0 | 2021-01-30 07:44:38.033 | info | (27390) Trying to connect as system.user.admin

But it is not Possible to Change the Config because its greyed out.

**Comment by GermanBluefox** [comment]
Please use 4.0.7 version

**Comment by spoeh-man** [comment]
4.0.7 is the same problem

**Comment by spoeh-man** [comment]
4.0.8 is Working
