### ISSUE TITLE
4.0.8 i can´t use admin from cloud

### ISSUE THREAD

**Issue by fuchs-1978** [ioBroker/ioBroker.cloud#167]
With 4.0.8 i can´t use admin from cloud. the popup sad "admin is not activated"

down to 4.0.7 is already okay

**Comment by GermanBluefox** [comment]
Is there any errors in browser console?

**Comment by fuchs-1978** [comment]
Die Meldung kommt wenn ich die Übersicht aufrufe
![image](https://user-images.githubusercontent.com/61315711/106455103-0494ed00-648c-11eb-9028-541dcaf7d19e.png)

Wenn ich dann auf Admin gehe kommt die Meldung:
![image](https://user-images.githubusercontent.com/61315711/106455241-360db880-648c-11eb-9257-12ae221f6f66.png)

mit diesem Hinweis im Browserlog:

![image](https://user-images.githubusercontent.com/61315711/106455298-4b82e280-648c-11eb-91d1-2cd96dc437c6.png)


Wobei ich die Meldung auch mit der 4.0.7 im Log bekomme. Nur das Browser PopUp erscheint nicht, sondern ganz normal der Admin Adapter. Also 4.0.8 Fehler, downgrade 4.0.7 wieder alles okay ohne Änderungen in der Config

**Comment by fuchs-1978** [comment]
4.0.9 works. thanks
