### ISSUE TITLE
iobroker cloud error received unknown command

### ISSUE THREAD

**Issue by rewe1978** [ioBroker/ioBroker.cloud#168]
Das ist im log zu sehr
Auf meinem Admin komm ich mit Cloud pro drauf 
Auf Editor vis und vis runtime nicht
Bleibt bei lade Widget Datensätze immer stehen
Lg

**Comment by Apollon77** [comment]
zeigt der browser in der konsole einen Fehelr an?

**Comment by Apollon77** [comment]
Welche cloud adapter version?

**Comment by rewe1978** [comment]
Hallo Danke für die rasche Antwort 

cloud adapter 4.0.4
Browser zeigt nichts an
Das kommt jetzt wenn ich auf vis runtime zugreifen will

cloud.0 | 2021-02-11 08:07:50.824 | error | (35434) Addon DashUI Cannot load widget set info Not Found
-- | -- | -- | --


Lg

**Comment by rewe1978** [comment]
Kann mir keiner weiterhelfen...Hahn leider auch keine Idee mehr 
Ports sind alle freigegeben 
Lg

**Comment by Apollon77** [comment]
Frage ... Oben schreibst DU Admin? Aber weiter unten vis? Was ist jetzt das Thema?

Log bitte vollständig

**Comment by rewe1978** [comment]
Sorry für das Missverständnis...aber habe oben schon gesagt vis editor und runtime geht nicht
Auf Admin komme ich ganz normal drauf 
Im log schreibt er mir dann
Dash UI cannot load widget set info
