### ISSUE TITLE
Nutzung SimpleApi über CloudPro

### ISSUE THREAD

**Issue by Siggi0904** [ioBroker/ioBroker.cloud#169]
Hallo,
ich würde gern den Akkustand und weitere Daten von meinem Handy an IOBroker übermitteln.
Gibt es hierzu eine Anleitung?

Muss dafür das "Simple RESTful API" installiert und eingerichtet sein?
Auf der Github-Startseite hier steht unter Services->SimpleApi
"Don't forget to add simpleApi to allowed services in the configuration."
Wie ist das zu verstehen? Wo muss das eingerichtet werden, wenn dafür das o.g. Plugin gemeint ist?

Die zu beschreibenden Datenpunkte liegen unter javascript.0 in einem Unterordner.

Großen Dank im Voraus bei der Unterstützung der Einrichtung.

**Comment by Apollon77** [comment]
Nein, der cloud Adapte rhat die relevanten Funktionen direkt eingebaut. DU musst aber in der Cloud Konfig bei der Whitelist der Services(Dienste das genannte "simpleApi" eintragen, damit diese Befehle durchgelassen werden, sonst wird das geblockt

**Comment by Siggi0904** [comment]
`https://iobroker.pro/service/simpleApi/<api-key>/set/javascript.0.Handys_Tablets.HandyMario.WIFI?value=true`
funktioniert super und kommt auch an.

Kann ich auch ein "bestätigt-flag" mitsenden?

**Comment by Apollon77** [comment]
no, this would be a feature request

**Comment by Siggi0904** [comment]
Okay, then I fill a feature request and close here.
