### ISSUE TITLE
Error not connected and Adapter status never stays green for a long time

### ISSUE THREAD

**Issue by easybeat** [ioBroker/ioBroker.cloud#178]
**Describe the bug**  
I have problems with my cloud adapter. It is working and I am able to connect when I restart the web1 instance and the cloud adapter but after a few hours when I try to connect again to iobroker.pro and VIS, I get an error vis not connected:

![Screenshot (03 03](https://user-images.githubusercontent.com/37217887/109827002-a77f8900-7c3b-11eb-9059-44588132ee69.png)

After the connection is no working, I get strange log entries in ioBroker

![Screenshot 2021-03-03 154550](https://user-images.githubusercontent.com/37217887/109826740-638c8400-7c3b-11eb-8184-81fe3c390992.png)

**To Reproduce**  
1. Start Cloud adapter instance
2. start web1 adapter instance
3. connect to iobroker.pro => VIS: Result VIS is working
4. wait a few hours
5. connect to iobroker.pro => VIS: Result error message "...not connected"

**Expected behavior**  
Connection via iobroker.pro to VIS should always work

**Versions:**  
 - Adapter version: 4.0.10
 - JS-Controller version: 3.2.16
 - Node version: 10.23.2
 - Operating system: Debian on Proxmox VM

Thanks for your help.

**Comment by easybeat** [comment]
New problem: The cloud adapter is connected but I can't access the VIS....

**Comment by Apollon77** [comment]
Error still that websocket error in your logs? What error you get ?
to be sure: autentication adn ssl is disabled for that web instance?

**Comment by easybeat** [comment]
![image](https://user-images.githubusercontent.com/37217887/111787437-37ba0100-88bf-11eb-81dc-14e744146fa0.png)

Web.1 looks like that but there is nothing coming in...I have no entries in Log

**Comment by easybeat** [comment]
There is absolutely nothing in the log for web1 if I try to connect!

So this seems not to work anymore!

**Comment by Apollon77** [comment]
Und web.1 ist im cloud Adapter konfiguriert?
Bitte mal Cloud adapter auf debug stelle und Log posten

**Comment by easybeat** [comment]
Da kommt absolut nichts durch
![image](https://user-images.githubusercontent.com/37217887/111914036-b99d5c00-8a70-11eb-8005-d2790b6c2059.png)

Könnte ein Problem auf Seite ioBroker.pro sein?

**Comment by GermanBluefox** [comment]
> Da kommt absolut nichts durch
> ![image](https://user-images.githubusercontent.com/37217887/111914036-b99d5c00-8a70-11eb-8005-d2790b6c2059.png)
> 
> Könnte ein Problem auf Seite ioBroker.pro sein?

Also. Das Problem ist nicht bekannt. Momentan kann ich nur ein Workaround anbieten: jeder Stunde cloud Adapter neu starten. Dabei connection String auf https://iobroker.pro:10556 ändern (Objekt  system.adapter.cliud.0 editieren)

Ansonsten alle andere Benutzer haben so ein Problem nicht. Man musste Socket.io Version in cloud Adapter checken.

**Comment by easybeat** [comment]
> > Da kommt absolut nichts durch
> > ![image](https://user-images.githubusercontent.com/37217887/111914036-b99d5c00-8a70-11eb-8005-d2790b6c2059.png)
> > Könnte ein Problem auf Seite ioBroker.pro sein?
> 
> Also. Das Problem ist nicht bekannt. Momentan kann ich nur ein Workaround anbieten: jeder Stunde cloud Adapter neu starten. Dabei connection String auf https://iobroker.pro:10556 ändern (Objekt system.adapter.cliud.0 editieren)
> 
> Ansonsten alle andere Benutzer haben so ein Problem nicht. Man musste Socket.io Version in cloud Adapter checken.

Da muss ich jetzt noch ein wenig Hilfe beanspruchen. Ich habe im Cloud.0 Objekt keinen connection string:
![image](https://user-images.githubusercontent.com/37217887/111955846-551ee300-8aea-11eb-816d-6ab9c88be462.png)

**Comment by easybeat** [comment]
Ich schliesse dieses Thema und öffne einen neuen Bug-Report
