### ISSUE TITLE
Can't connect to cloud service due too short timeout value

### ISSUE THREAD

**Issue by c-klinger** [ioBroker/ioBroker.cloud#19]
I wasn't able to connect to the cloud service (see http://forum.iobroker.net/viewtopic.php?f=37&t=7339), after some debugging i figgured out that the timeout was too low for my system.

It might be a good idea to make this value configurable in adapter configuration.

**Comment by GermanBluefox** [comment]
Does it work now?

**Comment by c-klinger** [comment]
yes, the #19 / #20 fixed the issue for me
