### ISSUE TITLE
Javascript Adapter unterstützt kein Rules

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.cloud#204]
Der Javascript Adapter beim Fernzugriff unterstützt noch kein Rules, was dazu führt dass es als Javascript Dateien angezeigt wird. Hier sollte asap ein update durchgeführt werden.

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/126035882-006a6020-4c29-4bea-b042-276ec87076ba.png)

Don't forget Shift+F5 (Cache löschen)
