### ISSUE TITLE
Anpassung Vis und Admin 5

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.cloud#212]
Hallo,

bitte die Vis und den Admin 5 für Pro User updaten.
Unter Vis bekomme ich einen Lizenzfehler und der Admin 5(GUI) funktioniert nicht.

https://forum.iobroker.net/topic/46123/vis-keine-g%C3%BCltige-lizenz-gefunden/26?page=2

`
<html>
<body>

cloud.0 | 2021-07-12 11:05:55.780 | error | Addon DashUI 10 - at Function.renderTo (https://iobroker.pro/vis/lib/js/can.custom.min.js:58:2982)
-- | -- | -- | --
cloud.0 | 2021-07-12 11:05:55.779 | error | Addon DashUI 9 - at r (https://iobroker.pro/vis/lib/js/can.custom.min.js:58:131)
cloud.0 | 2021-07-12 11:05:55.779 | error | Addon DashUI 8 - at Function.frag (https://iobroker.pro/vis/lib/js/can.custom.min.js:58:1344)
cloud.0 | 2021-07-12 11:05:55.753 | error | Addon DashUI 7 - at Function.hookup (https://iobroker.pro/vis/lib/js/can.custom.min.js:58:1751)
cloud.0 | 2021-07-12 11:05:55.752 | error | Addon DashUI 6 - at Object.a.each (https://iobroker.pro/vis/lib/js/can.custom.min.js:24:294)
cloud.0 | 2021-07-12 11:05:55.752 | error | Addon DashUI 5 - at HTMLDivElement.<anonymous> (https://iobroker.pro/vis/lib/js/can.custom.min.js:58:1841)
cloud.0 | 2021-07-12 11:05:55.752 | error | Addon DashUI 4 - at https://iobroker.pro/vis/lib/js/can.custom.min.js:64:6147
cloud.0 | 2021-07-12 11:05:55.750 | error | Addon DashUI 3 - at Object.a.each (https://iobroker.pro/vis/lib/js/can.custom.min.js:24:294)
cloud.0 | 2021-07-12 11:05:55.750 | error | Addon DashUI 2 - at Function.<anonymous> (https://iobroker.pro/vis/lib/js/can.custom.min.js:64:6166)
cloud.0 | 2021-07-12 11:05:55.750 | error | Addon DashUI 1 - at Object.eval (tplVis-materialdesign-Table.js:37:92)
cloud.0 | 2021-07-12 11:05:55.746 | error | Addon DashUI 0 - TypeError: Cannot read property 'handle' of undefinedTypeError: Cannot read property 'handle' of undefined
cloud.0 | 2021-07-12 11:05:55.045 | error | Addon DashUI can't render tplVis-materialdesign-Table w00075 on "main":

</body>
</html>`

Plattform: Windows
RAM: 16 GB 
Node.js: 12.22.1
NPM: 6.14.12
JS Controller: 3.3.14
Admin: 5.1.10
Web: 3.4.3
Socket.io: 3.1.4
Script Engine: 5.2.3
IOT: 1.8.22
VIS: 1.4.2
HM-Rega: 3.0.29
HM-RPC: 1.14.43
Jarvis: 3.0.0
Backitup: 2.1.12
Cloud: 4.0.11
ICal: 1.9.3
iQontrol: 1.8.0
fb-checkpresence: 1.1.5
Hue: 3.5.19
Alexa2: 3.9.3

MFG
Sigi

**Comment by Apollon77** [comment]
Admin 5 wird erst kommen wenn er im Stable ist denke ich ...
