### ISSUE TITLE
Zugriff auf Scripte über Pro-Server geht nicht mehr

### ISSUE THREAD

**Issue by Baenker** [ioBroker/ioBroker.cloud#213]
Ich habe keinen Zugriff mehr auf die Scripte über den Pro Server. Alles andere funktioniert wie immer. Log ist leer.

Cloud 4.01
iot 1.8.22
admin: 4.21
js-controller: 3.2.16
javascript: 5.1.3

Alle Seiten funktionieren nur auf die Scripte habe ich keinen Zugriff. Dort dreht sich nur der Kreis. Gestern Abend ging es noch. Hat evtl jemand Updates auf dem Server eingespielt?

Klicke auf auf "Javascript" im Menü kommt ein einzelner Eintrag im Log:

`cloud.0	2021-07-14 08:36:35.630	error	(32630) Received unknown command 1: getAdapterInstances `

Was ich noch in den Logs gefunden habe:

> iot.0	2021-07-14 00:40:16.853	info	(1048) Connection lost
iot.0	2021-07-14 00:40:16.839	info	(1048) Connection changed: disconnect
cloud.0	2021-07-14 00:39:48.960	error	(508) Error while connecting to cloud: timeout
cloud.0	2021-07-14 00:39:08.924	error	(508) Ping timeout`

Dann geht es weiter:

> iot.0	2021-07-14 00:47:30.103	info	(1048) Connection changed: connect
host.iobroker_V51	2021-07-14 00:45:40.544	info	instance system.adapter.cloud.0 started with pid 32630
iot.0	2021-07-14 00:45:21.864	info	(1048) Connection changed: disconnect
host.iobroker_V51	2021-07-14 00:45:10.512	info	Restart adapter system.adapter.cloud.0 because enabled
host.iobroker_V51	2021-07-14 00:45:10.512	error	instance system.adapter.cloud.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker_V51	2021-07-14 00:45:10.508	error	Caught by controller[0]: Error:
cloud.0	2021-07-14 00:45:10.190	warn	(508) Terminated (UNCAUGHT_EXCEPTION): Without reason
cloud.0	2021-07-14 00:45:10.154	error	(508)
cloud.0	2021-07-14 00:45:10.154	error	(508) Error:
cloud.0	2021-07-14 00:45:10.153	error	(508) uncaught exception:
cloud.0	2021-07-14 00:44:48.948	error	(508) Error while connecting to cloud: timeout
cloud.0	2021-07-14 00:44:18.948	error	(508) Error while connecting to cloud: timeout

Danach war ruhe im log und es kamen nur die normalen Meldungen. ioBroker hatte also ca. 8 Minuten Probleme sich mit der Cloud zu verbinden.

**Comment by Apollon77** [comment]
Ich kann mir gut vorstellen das es hier inkompatibilitäten mit dem Admin4 gibt welches auf Cloud verfügbar ist. versuch mal javascript zu downgraden

**Comment by Baenker** [comment]
Javascript ist 5.1.3  (die funktioniert mit admi v4 die ich zu Hause installiert habe.) und dem Tag zuvor ging die Version noch. Welche Version soll ich testen?

Ich habe den Tag davor das ganze noch genutzt ohne danach einen Adapter zu aktualisieren. Ich vermute oder hoffe das es eher nicht an meiner Installation liegt?

**Comment by Baenker** [comment]
Habe beim Javascript Adapter zufällig folgendes Issue gesehen:

https://github.com/ioBroker/ioBroker.javascript/issues/827

Kann es damit zusammen hängen? Lokal geht es zwar bei mir aber ich glaube ich habe am Tag zuvor einige alte Scripte per Cloud gelöscht!?

Außerdem habe ich noch einen Screenshot. Vielleicht hilft der ja weiter

<img width="1680" alt="Bildschirmfoto 2021-07-16 um 19 10 45" src="https://user-images.githubusercontent.com/22763577/125984982-cbd94d23-af83-41fe-9e78-49bd57973e85.png">

403 Forbidden bei Sentry.

**Comment by Apollon77** [comment]
403 bei Sentry ist ok und absicht so.

Bluefox ist am Issue dran

**Comment by GermanBluefox** [comment]
Please update cloud adapter to 4.1.0

**Comment by Baenker** [comment]
Super Vielen Dank.

**Comment by Baenker** [comment]
Sorry. Vergessen zu schließen und zu schreiben das es geht.

**Comment by MSchmitt67** [comment]
Hallo,
ich weiß nicht ob es hier her gehört, aber dass war das einziges was ich im web finden konnte mit einer ähnlichen Fehlermeldung.
Ich nutze die Android App für Material und seit dem update des cloud Adapters steht im Iobroker Log immer wenn die App nutze.
`<html>
<body>


cloud.0 | 2022-08-20 13:43:32.118 | error | Received unknown command 1: name
-- | -- | -- | --



</body>
</html>`

funktionieren tut aber scheinbar alles wie es soll. Soll ich das einfach ignorieren oder kann man da was machen ?
