### ISSUE TITLE
Vis über die Cloud Fehler für materialdesign widget

### ISSUE THREAD

**Issue by weindler** [ioBroker/ioBroker.cloud#214]
Würde gerne die Offline Lizenz buchen, dabei ist mir aufgefallen wenn ich über die Cloud auf die Vis zugreifen will, bekomme ich etliche Fehler im log. Dies liegt wahrscheinlich alles am material design widget, denn die Navigation ist auch weg.

`
<html><body>

cloud.0 | 2021-07-14 16:24:38.194 | error | (30625) Addon DashUI  33 -
-- | -- | -- | --
cloud.0 | 2021-07-14 16:24:38.192 | error | (30625) Addon DashUI  32 - n.prototype.addEventListeners/this.ws.onmessage@https://iobroker.net/lib/js/socket.io.js:3:1447
cloud.0 | 2021-07-14 16:24:38.191 | error | (30625) Addon DashUI  31 - n.prototype.onData@https://iobroker.net/lib/js/socket.io.js:2:17947
cloud.0 | 2021-07-14 16:24:38.189 | error | (30625) Addon DashUI  30 - n.prototype.onPacket@https://iobroker.net/lib/js/socket.io.js:2:17998
cloud.0 | 2021-07-14 16:24:38.187 | error | (30625) Addon DashUI  29 - n.prototype.emit@https://iobroker.net/lib/js/socket.io.js:2:28725
cloud.0 | 2021-07-14 16:24:38.186 | error | (30625) Addon DashUI  28 - n.prototype.setTransport/<@https://iobroker.net/lib/js/socket.io.js:2:3527
cloud.0 | 2021-07-14 16:24:38.180 | error | (30625) Addon DashUI  27 - n.prototype.onPacket@https://iobroker.net/lib/js/socket.io.js:2:5906
cloud.0 | 2021-07-14 16:24:38.179 | error | (30625) Addon DashUI  26 - n.prototype.emit@https://iobroker.net/lib/js/socket.io.js:2:28725
cloud.0 | 2021-07-14 16:24:38.177 | error | (30625) Addon DashUI  25 - t.exports/<@https://iobroker.net/lib/js/socket.io.js:3:7486
cloud.0 | 2021-07-14 16:24:38.176 | error | (30625) Addon DashUI  24 - n.prototype.ondata@https://iobroker.net/lib/js/socket.io.js:1:29203
cloud.0 | 2021-07-14 16:24:38.174 | error | (30625) Addon DashUI  23 - s.prototype.add@https://iobroker.net/lib/js/socket.io.js:1:10407
cloud.0 | 2021-07-14 16:24:38.173 | error | (30625) Addon DashUI  22 - r.prototype.emit@https://iobroker.net/lib/js/socket.io.js:1:23662
cloud.0 | 2021-07-14 16:24:38.172 | error | (30625) Addon DashUI  21 - t.exports/<@https://iobroker.net/lib/js/socket.io.js:3:7486
cloud.0 | 2021-07-14 16:24:38.171 | error | (30625) Addon DashUI  20 - n.prototype.ondecoded@https://iobroker.net/lib/js/socket.io.js:1:29250
cloud.0 | 2021-07-14 16:24:38.169 | error | (30625) Addon DashUI  19 - n.prototype.emit@https://iobroker.net/lib/js/socket.io.js:2:28725
cloud.0 | 2021-07-14 16:24:38.168 | error | (30625) Addon DashUI  18 - t.exports/<@https://iobroker.net/lib/js/socket.io.js:3:7486
cloud.0 | 2021-07-14 16:24:38.167 | error | (30625) Addon DashUI  17 - n.prototype.onpacket@https://iobroker.net/lib/js/socket.io.js:3:5417
cloud.0 | 2021-07-14 16:24:38.165 | error | (30625) Addon DashUI  16 - n.prototype.onack@https://iobroker.net/lib/js/socket.io.js:3:6057
cloud.0 | 2021-07-14 16:24:38.164 | error | (30625) Addon DashUI  15 - getStates/<@https://iobroker.net/vis/js/conn.js:792:29
cloud.0 | 2021-07-14 16:24:38.160 | error | (30625) Addon DashUI  14 - subscribeStates/<@https://iobroker.net/vis/js/vis.js:2865:31
cloud.0 | 2021-07-14 16:24:38.159 | error | (30625) Addon DashUI  13 - renderView/<@https://iobroker.net/vis/js/vis.js:916:120
cloud.0 | 2021-07-14 16:24:38.157 | error | (30625) Addon DashUI  12 - renderWidget@https://iobroker.net/vis/js/vis.js:1629:33
cloud.0 | 2021-07-14 16:24:38.156 | error | (30625) Addon DashUI  11 - e.template@https://iobroker.net/vis/lib/js/can.custom.min.js:58:1267
cloud.0 | 2021-07-14 16:24:38.155 | error | (30625) Addon DashUI  10 - renderAs@https://iobroker.net/vis/lib/js/can.custom.min.js:58:3631
cloud.0 | 2021-07-14 16:24:38.153 | error | (30625) Addon DashUI  9 - renderTo@https://iobroker.net/vis/lib/js/can.custom.min.js:58:2982
cloud.0 | 2021-07-14 16:24:38.149 | error | (30625) Addon DashUI  8 - r@https://iobroker.net/vis/lib/js/can.custom.min.js:58:131
cloud.0 | 2021-07-14 16:24:38.148 | error | (30625) Addon DashUI  7 - frag@https://iobroker.net/vis/lib/js/can.custom.min.js:58:1344
cloud.0 | 2021-07-14 16:24:38.147 | error | (30625) Addon DashUI  6 - hookup@https://iobroker.net/vis/lib/js/can.custom.min.js:58:1751
cloud.0 | 2021-07-14 16:24:38.146 | error | (30625) Addon DashUI  5 - a.each@https://iobroker.net/vis/lib/js/can.custom.min.js:24:294
cloud.0 | 2021-07-14 16:24:38.144 | error | (30625) Addon DashUI  4 - hookup/<@https://iobroker.net/vis/lib/js/can.custom.min.js:58:1841
cloud.0 | 2021-07-14 16:24:38.141 | error | (30625) Addon DashUI  3 - can.view.pending/<@https://iobroker.net/vis/lib/js/can.custom.min.js:64:6147
cloud.0 | 2021-07-14 16:24:38.140 | error | (30625) Addon DashUI  2 - a.each@https://iobroker.net/vis/lib/js/can.custom.min.js:24:294
cloud.0 | 2021-07-14 16:24:38.139 | error | (30625) Addon DashUI  1 - can.view.pending/</<@https://iobroker.net/vis/lib/js/can.custom.min.js:64:6167
cloud.0 | 2021-07-14 16:24:38.138 | error | (30625) Addon DashUI  0 - TypeError: vis.binds.materialdesign.textfield  is undefinedthis.fn/</<@tplVis-materialdesign-Input.js:29:61
cloud.0 | 2021-07-14 16:24:38.135 | error | (30625) Addon DashUI  can't render tplVis-materialdesign-Input w00295 on "Josef_Zimmer":

</body>
</html>`

Kann mir hier jemand helfen, danke.
Node.js
    v12.22.2 
NPM
    6.14.13

Cloud Adapter:
4.011

**Comment by GermanBluefox** [comment]
please try again

**Comment by weindler** [comment]
hi, nein leider nicht besser geworden, immer noch die allergleichen fehler.

**Comment by Bavarialex** [comment]
hier genauso "böse"

`<html>
<body>


2022-01-04 17:38:21.825 - error: cloud.0 (31733) Addon vis 0 - Error: can.view: No template or empty template:tplMetroTileNav.ejsError: can.view: No template or empty template:tplMetroTileNav.ejs
--
2022-01-04 17:38:21.826 - error: cloud.0 (31733) Addon vis 1 - at u (https://iobroker.pro/vis/lib/js/can.custom.min.js:58:256)
2022-01-04 17:38:21.827 - error: cloud.0 (31733) Addon vis 2 - at Object.error (https://iobroker.pro/vis/lib/js/can.custom.min.js:58:953)
2022-01-04 17:38:21.828 - error: cloud.0 (31733) Addon vis 3 - at j (https://iobroker.pro/lib/js/jquery-1.11.2.min.js:2:27295)
2022-01-04 17:38:21.829 - error: cloud.0 (31733) Addon vis 4 - at Object.fireWith [as rejectWith] (https://iobroker.pro/lib/js/jquery-1.11.2.min.js:2:28108)
2022-01-04 17:38:21.830 - error: cloud.0 (31733) Addon vis 5 - at x (https://iobroker.pro/lib/js/jquery-1.11.2.min.js:4:22086)
2022-01-04 17:38:21.831 - error: cloud.0 (31733) Addon vis 6 - at b (https://iobroker.pro/lib/js/jquery-1.11.2.min.js:4:25980)
2022-01-04 17:38:21.832 - error: cloud.0 (31733) Addon vis 7 - at Object.send (https://iobroker.pro/lib/js/jquery-1.11.2.min.js:4:26084)
2022-01-04 17:38:21.833 - error: cloud.0 (31733) Addon vis 8 - at Object.ajax (https://iobroker.pro/lib/js/jquery-1.11.2.min.js:4:21520)
2022-01-04 17:38:21.835 - error: cloud.0 (31733) Addon vis 9 - at o (https://iobroker.pro/vis/lib/js/can.custom.min.js:58:899)
2022-01-04 17:38:21.836 - error: cloud.0 (31733) Addon vis 10 - at https://iobroker.pro/vis/lib/js/can.custom.min.js:46:3358
2022-01-04 17:38:21.837 - error: cloud.0 (31733) Addon vis can't render tplMetroTileNav w00894 on "metro_home":


</body>
</html>`

NODE.JS: V14.18.2
NPM: 6.14.15
VIS: 1.4.5
admin:5.2.3
WEB: 3.4.9
