### ISSUE TITLE
Anmeldung Cloud Adapter

### ISSUE THREAD

**Issue by gold2605** [ioBroker/ioBroker.cloud#215]
Hallo,

seit mehreren Wochen funktioniert die Anmeldung des Cloud Adapters nicht mehr. Pro ist bis 01/2022 vorhanden, Anmeldung über neuen Key auch probiert. Fehlermeldung siehe Bild….. Adapter wurde schon neu installiert 

vielen Dank

![435FB46A-2288-4C74-BA82-E70DFC2A44E8](https://user-images.githubusercontent.com/39046800/126028683-97636f4c-cc7a-4590-9857-ed8c363e4d8a.png)

**Comment by GermanBluefox** [comment]
Please test 4.1.0, but it looks like corrupt file system: https://forum.iobroker.net/topic/28082/bei-zugriff-st%C3%BCrzt-iobroker-admin-ab/2

**Comment by GermanBluefox** [comment]
Or may be it is node16? https://github.com/ioBroker/ioBroker.cloud/issues/203

**Comment by gold2605** [comment]
Hallo, nein, es läuft die node 12.22

**Comment by ChrissT23** [comment]
Hallo, 
ich habe ein ähnliches Problem. Ich musste gestern Abend mein System per Backup neu einspielen. Seitdem geht alles bis auf der Cloud adapter, der bleibt Rot. Vor dem Backup lief alles ohne Probleme. CloudPro habe ich gerade erst neu gekauft. 
Cloud Version 4.1.0 ist installiert 
System: 
Raspberry Pi4B
NPM: 6.14.15
NodeJS: 14.18.2
JScontroller: 3.3.21

`<html><body>


host.raspberrypi | 2021-12-19 10:08:26.106 | error | instance system.adapter.cloud.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.raspberrypi | 2021-12-19 10:08:26.106 | error | Caught by controller[0]:     at TLSSocket.emit (domain.js:475:12)
host.raspberrypi | 2021-12-19 10:08:26.105 | error | Caught by controller[0]:     at TLSSocket.emit (events.js:400:28)
host.raspberrypi | 2021-12-19 10:08:26.105 | error | Caught by controller[0]:     at TLSSocket.realHandler (/opt/iobroker/node_modules/ws/lib/WebSocket.js:825:20)
host.raspberrypi | 2021-12-19 10:08:26.105 | error | Caught by controller[0]:     at Receiver.add (/opt/iobroker/node_modules/ws/lib/Receiver.js:103:24)
host.raspberrypi | 2021-12-19 10:08:26.105 | error | Caught by controller[0]:     at Receiver.expectHandler (/opt/iobroker/node_modules/ws/lib/Receiver.js:499:31)
host.raspberrypi | 2021-12-19 10:08:26.105 | error | Caught by controller[0]:     at Receiver.finish (/opt/iobroker/node_modules/ws/lib/Receiver.js:541:12)
host.raspberrypi | 2021-12-19 10:08:26.105 | error | Caught by controller[0]:     at Receiver.flush (/opt/iobroker/node_modules/ws/lib/Receiver.js:347:3)
host.raspberrypi | 2021-12-19 10:08:26.104 | error | Caught by controller[0]:     at /opt/iobroker/node_modules/ws/lib/Receiver.js:508:14
host.raspberrypi | 2021-12-19 10:08:26.104 | error | Caught by controller[0]:     at Receiver.applyExtensions (/opt/iobroker/node_modules/ws/lib/Receiver.js:371:5)
host.raspberrypi | 2021-12-19 10:08:26.104 | error | Caught by controller[0]:     at /opt/iobroker/node_modules/ws/lib/Receiver.js:532:29
host.raspberrypi | 2021-12-19 10:08:26.104 | error | Caught by controller[0]: TypeError: Cannot read property 'isValidUTF8' of undefined
cloud.0 | 2021-12-19 10:08:25.884 | warn | (2462) Terminated (UNCAUGHT_EXCEPTION): Without reason
cloud.0 | 2021-12-19 10:08:25.881 | info | (2462) terminating
cloud.0 | 2021-12-19 10:08:25.849 | error | (2462) Cannot read property 'isValidUTF8' of undefined
cloud.0 | 2021-12-19 10:08:25.848 | error | at TLSSocket.emit (domain.js:475:12)
cloud.0 | 2021-12-19 10:08:25.848 | error | at TLSSocket.emit (events.js:400:28)
cloud.0 | 2021-12-19 10:08:25.848 | error | at TLSSocket.realHandler (/opt/iobroker/node_modules/ws/lib/WebSocket.js:825:20)
cloud.0 | 2021-12-19 10:08:25.848 | error | at Receiver.add (/opt/iobroker/node_modules/ws/lib/Receiver.js:103:24)
cloud.0 | 2021-12-19 10:08:25.848 | error | at Receiver.expectHandler (/opt/iobroker/node_modules/ws/lib/Receiver.js:499:31)
cloud.0 | 2021-12-19 10:08:25.848 | error | at Receiver.finish (/opt/iobroker/node_modules/ws/lib/Receiver.js:541:12)
cloud.0 | 2021-12-19 10:08:25.848 | error | at Receiver.flush (/opt/iobroker/node_modules/ws/lib/Receiver.js:347:3)
cloud.0 | 2021-12-19 10:08:25.848 | error | at /opt/iobroker/node_modules/ws/lib/Receiver.js:508:14
cloud.0 | 2021-12-19 10:08:25.848 | error | at Receiver.applyExtensions (/opt/iobroker/node_modules/ws/lib/Receiver.js:371:5)
cloud.0 | 2021-12-19 10:08:25.848 | error | at /opt/iobroker/node_modules/ws/lib/Receiver.js:532:29
cloud.0 | 2021-12-19 10:08:25.848 | error | (2462) TypeError: Cannot read property 'isValidUTF8' of undefined
cloud.0 | 2021-12-19 10:08:25.847 | error | (2462) uncaught exception: Cannot read property 'isValidUTF8' of undefined
cloud.0 | 2021-12-19 10:08:25.750 | info | (2462) Trying to connect as system.user.admin


</body>
</html>`
