### ISSUE TITLE
Automatische Erzeugung von Smart-Names buggy?

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.cloud#22]
Siehe http://forum.iobroker.net/viewtopic.php?f=37&t=8027

**Comment by GermanBluefox** [comment]
Immer noch aktuell?

**Comment by AlCalzone** [comment]
Lange nicht mehr getestet, werde ich probieren.

**Comment by AlCalzone** [comment]
Müsste nochmal gecheckt werden aber ich scheue mich, mir die funktionierende Konfiguration zu zerschießen.
