### ISSUE TITLE
About server side code for ioBroker.cloud

### ISSUE THREAD

**Issue by leoujz** [ioBroker/ioBroker.cloud#24]
Through cloud of iobroker.net, I can access my local installation of ioBroker after assigning the app-key. And I want to know that if I can install ioBroker cloud on my own server? Or is the server side code for ioBroker cloud public under certain license?

**Comment by GermanBluefox** [comment]
No. There is no public code for server. But you can write your own. It is
not so complicated.

21 окт. 2017 г. 4:43 пользователь "leoujz" <notifications@github.com>
написал:

**Comment by leoujz** [comment]
Thanks very much
