### ISSUE TITLE
Pro license is not recogniced.

### ISSUE THREAD

**Issue by thomasklein1975** [ioBroker/ioBroker.cloud#244]
Hi,

the usage of my pro key is not possible. I want to use adapter for getting information from out of my network.

![grafik](https://user-images.githubusercontent.com/47893316/136253623-08e94600-a000-4e68-8d31-d9ceaa97571a.png)

Here is the log:

`cloud.0	2021-10-06 19:14:47.375	info	(7157) Got terminate signal TERMINATE_YOURSELF
cloud.0	2021-10-06 19:14:47.372	info	(7157) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
cloud.0	2021-10-06 19:14:42.293	info	(7157) Connection lost
cloud.0	2021-10-06 19:14:42.292	info	(7157) Connection changed: io client disconnect
cloud.0	2021-10-06 19:14:42.290	error	(7157) Please buy remote access to use pro. If you did it, please wait 5 minutes.
cloud.0	2021-10-06 19:14:42.289	warn	(7157) Adapter stopped. Reason: command from server
cloud.0	2021-10-06 19:14:42.241	info	(7157) Connection changed: connect
cloud.0	2021-10-06 19:14:41.986	info	(7157) Trying to connect as system.user.admin
cloud.0	2021-10-06 19:14:11.958	info	(7157) Adapter redirected temporally to "https://iobroker.pro:10556" in 30 seconds. Reason: command from server
cloud.0	2021-10-06 19:14:11.911	info	(7157) Connection changed: connect
cloud.0	2021-10-06 19:14:11.577	info	(7157) Trying to connect as system.user.admin
cloud.0	2021-10-06 19:14:11.374	info	(7157) Connecting with https://iobroker.pro:10555 with "............."
cloud.0	2021-10-06 19:14:11.281	info	(7157) starting. Version 4.1.0 in /opt/iobroker/node_modules/iobroker.cloud, node: v14.17.0, js-controller: 3.3.15
`

**Comment by thomasklein1975** [comment]
thx, done

**Comment by Apollon77** [comment]
iobroker.pro you can purchase the Remote access package ... thats you need ... also availabel https://iobroker.pro/www/pricing

**Comment by thomasklein1975** [comment]
a ok thx, there a serveral kind/combinations of pro variations
