### ISSUE TITLE
Cannot configure whitelist.

### ISSUE THREAD

**Issue by derherrgraf** [ioBroker/ioBroker.cloud#257]
**Describe the bug**  
I try to use text2cmds and get `Received service "text2command", but it is not found in whitelist`. After this i look into the config and cant see any whitelist, only the label. Is this correct?

![image](https://user-images.githubusercontent.com/16402094/143204266-7838c89c-575e-4d10-ad1f-c83eea88552c.png)

**Comment by Apollon77** [comment]
Seems like the field for the whitelist is missing ... strange

"type chips" ... @GermanBluefox something missing in Admin?

**Comment by djmarc75** [comment]
same Problem here...
I have exported the config as JSON, opened in Editor and typed in manually my Service, stored and imported it in the adapter settings.
But i think its not a good solution so it been solved soon

**Comment by Cabohne** [comment]
Same Problem here.
Admin 5.1.25
Cloud 4.1.0
Think I'll try to export the JSON, edit it and import it again, too.

**Comment by Apollon77** [comment]
@GermanBluefox Admin issue or jsoncinfig issue in cloud?

**Comment by Schimi1983** [comment]
Hi,
habe das gleiche... sobald ich im Admin Adapter die alte ansicht aktiviere ist das feld wieder da:

alte Ansicht
![image](https://user-images.githubusercontent.com/4581474/147670874-482172c3-6570-4c6c-a3e0-584f908feff0.png)
