### ISSUE TITLE
Alexa erkennt alle Geräte als Licht

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.cloud#26]
Siehe http://forum.iobroker.net/viewtopic.php?f=37&t=8791
Stimmt hier etwas am Cloud-Adapter nicht?

**Comment by Omega236** [comment]
Hallo,

habe das gleiche Problem, 
level.blind hat wie jeder dimmer (an aus % ↑ ↓)
Obwohl ich den Sinn von an aus nicht verstehe da man nie sagt "Schalte den Rolladen aus".
Dadurch kann man aber nicht der Gruppe sagen schalte aus da immer der Rolladen mit fährt.

Hoffe das ändert sich oder man kann es zumindest konfigurieren

**Comment by GermanBluefox** [comment]
Das war die Idee, statt zu sagen "Setzte die Rollladen auf 100%", man kann sagen "Schalte die Rollladen an".
Klingt blöd, aber stört doch keinem, oder?

**Comment by AlCalzone** [comment]
> Klingt blöd

Das ist eigentlich der Hauptpunkt. Ich kenne mich da nicht so gut aus. Gibts noch andere Gerätearten in Alexa, die möglicherweise natürlichere Sprache zulassen?

**Comment by modmax** [comment]
Dürfte doch durch #40 auch gelöst sein ...

**Comment by AlCalzone** [comment]
Ich schau mir das später nochmal an und schließe wenn es wirklich gelöst ist.

**Comment by AlCalzone** [comment]
Ist gelöst durch #40
