### ISSUE TITLE
keine Verbindung mehr zu Jarvis über ioBroker.pro

### ISSUE THREAD

**Issue by Ptikbrn** [ioBroker/ioBroker.cloud#269]
ChunkLoadError: Loading chunk 3 failed. (error: https://iobroker.pro/jarvis/static/js/3.c8fe7309.chunk.js)
a.e@https://iobroker.pro/jarvis/index.html:1:3416
i@https://iobroker.pro/jarvis/static/js/main.08fc3d34.chunk.js:1:1148176
y/t<@https://iobroker.pro/jarvis/static/js/main.08fc3d34.chunk.js:1:306699
_s/<@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1069198
_s@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1069347
bl@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1061293
ml@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1061216
sl@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1058225
Xi/<@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1009596
t.unstable_runWithPriority@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1084998
qi@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1009305
Xi@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1009543
Gi@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1009476
nl@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1055007
enqueueSetState@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1013304
w.prototype.setState@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:959043
value/</</<@https://iobroker.pro/jarvis/static/js/main.08fc3d34.chunk.js:1:276099
h.prototype.onack@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:717129
h.prototype.onpacket@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:716534
e.exports/<@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:718470
r.prototype.emit@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:275264
h.prototype.ondecoded@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:708019
e.exports/<@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:718470
r.prototype.emit@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:275264
d.prototype.add@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:393904
h.prototype.ondata@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:707972
e.exports/<@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:718470
r.prototype.emit@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:275264
u.prototype.onPacket@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1109707
u.prototype.setTransport/<@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1107310
r.prototype.emit@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:275264
o.prototype.onPacket@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:396558
o.prototype.onData@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:396507
f.prototype.addEventListeners/this.ws.onmessage@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1128323

das wird mir bei aufrufen über 
iobroker.pro/jarvis/Index.html 
angezeigt 

der Entwickler von Jarvis verweist auf Cloud Adapter kann es aber auch selbst nicht prüfen da kein ioBroker.pro Account vorhanden

**Comment by Apollon77** [comment]
Was ist denn passiert? Gabs ein Jarvis Update vllt nach dem es nicht mehr tat oder so? Am Cloud server hat sich nichts geändert

**Comment by Ptikbrn** [comment]
ja es gab das Update auf Version 3 von Jarvis ..... irgendwie möchte aber
der Entwickler nicht helfen oder kann es nicht .... ich habe extra
iobroker.pro mit Fernzugriff gebucht damit ich jarvis auch von unterwegs
bedienen kann und jetzt tut sich dies bezüglich nichts mehr ..... leider



Ingo Fischer ***@***.***> schrieb am Di., 4. Jan. 2022, 13:55:

**Comment by Apollon77** [comment]
na dfann downgrade doch malo auf die version die vorher drauf war. Es ist so: die ganzen echten dateien die im browser geladen werden kommen nicht von deinem host sondern von einer stabilen version die auf dem cloud server liefgt. Wenn also der Dev hier inkompatible änderungen macht gibts ein Problem ... 2->3 klingt für mich nach sowas

Wenn es nach downgrade geht dann bitte ein Cloud Adapter issue anlegen welches sagt" bitte Jarvis auf cloud server auf vX updaten ... aber die sollte echt stabil sein, weil das dann ALLE user betrifft die Jarvis über cloud nutzen

**Comment by Ptikbrn** [comment]
habe ja über Facebook schon mehrere gefunden die sich darüber ärgern ....
downgrade geht wohl laut Entwickler nicht sprich dann ist mein gesamtes
Jarvis hin .... ich weiß ja das es bis V2 noch lief erst seit v3 ist der
Fehler da also kann es nur daran liegen .... vllt Mal in Kontakt mit dem
Entwickler treten ? ich habe es versucht und mehr als issue in
iobroker.cloud Adapter erstellen habe ich nicht gehört da er wohl selbst
nicht testen kann.....

Ingo Fischer ***@***.***> schrieb am Di., 4. Jan. 2022, 14:07:

**Comment by Ptikbrn** [comment]
Problem Word auch sein viele wollen bei V2 bleiben andere hingegen habe
schon v3 am laufen sprich es müssten ja dann beide Versionen im Cloud
Server liegen damit alle den Fernzugriff haben falls keine vpn wie ich
...... habe von leider bis heute nicht hinbekommen über deutsche Glasfaser
und ipv6 .....

Patrick B ***@***.***> schrieb am Di., 4. Jan. 2022, 14:10:

**Comment by Ptikbrn** [comment]
vllt haben sie auch einen Tipp für mich wie ich wieder vpn bekomme dann
kann das auch erstmal so bleiben ☺️

Patrick B ***@***.***> schrieb am Di., 4. Jan. 2022, 14:13:

**Comment by Apollon77** [comment]
> Problem Word auch sein viele wollen bei V2 bleiben andere hingegen habe
schon v3 am laufen sprich es müssten ja dann beide Versionen im Cloud
Server liegen 

und genau das geht mit der aktuellen Struktur der cloud nicht.

**Comment by Ptikbrn** [comment]
hätten sie vllt einen Tipp für mich von herzustellen bei einem ds Lite
Anschluss ( echte ipv6 nach außen und innen , simulierte ipv4 nach außen
aber nicht innen ) Fritzbox kann es nicht und wireguard auf einem unraid
system klappt irgendwie auch nicht

Ingo Fischer ***@***.***> schrieb am Di., 4. Jan. 2022, 14:24:

**Comment by Apollon77** [comment]
Ich denke sowas gehört eher ins Forum :-)

**Comment by Ptikbrn** [comment]
wollte einfach Mal Frage , da ich ja gerade so einen netten Kontakt habe
der Schenkel geholfen und aufgeklärt hat 😁

Ingo Fischer ***@***.***> schrieb am Di., 4. Jan. 2022, 14:28:

**Comment by Sev7eNup** [comment]
Schließe mich dem Wunsch an die neue Jarvis Version mit iobroker.pro etc. kompatibel zu machen.
