### ISSUE TITLE
Fix: Crash Absturz, wenn die Farbe von Lampen über Echo gesteuert wird

### ISSUE THREAD

**Issue by oliverschulze** [ioBroker/ioBroker.cloud#27]
Hallo,

ich habe einen Fix für das Problem, dass iobroker.cloud abstürzt, wenn man über Echo die Farbe ändern möchte.
Zudem habe ich auch noch einen Fix dafür, dass, wenn man die Helligkeit solcher Lampen steuert, dass sich dabei die Farbe (hue), sowie die Farblichkeit (saturation) ändert.

Die Änderungen sind im angehängten File. Leider habe ich keine Push Rechte, sonst hätte ich es direkt ins Repository geschrieben.
[alexaSmartHomeV2.zip](https://github.com/ioBroker/ioBroker.cloud/files/1461288/alexaSmartHomeV2.zip)

**Comment by DutchmanNL** [comment]
Hi oliverschulze,

Auf github muesstest du die repositoriy forken, daarin deine aenderungen machen und dan kannst du einen push request auf den master machen.

Greetz,

Dutch

**Comment by oliverschulze** [comment]
ah super, danke, mache ich

**Comment by DutchmanNL** [comment]
Super danke! habe den pull gesehen dan kan sich der entwickler das mal anschauen

**Comment by modmax** [comment]
Ist wohl mit #40 und #42 gefixt.
Mit der aktuellen Version besteht keion Problem mehr und kann daher als gelöst betrachtet werden.
