### ISSUE TITLE
Adapter Config: neuer manueller Datenpunkt zerstört die Tabelle der Smartgeräte

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.cloud#29]
Siehe:
http://forum.iobroker.net/viewtopic.php?f=22&t=9069#p96987

![image](https://user-images.githubusercontent.com/11463809/32907042-114febf0-caff-11e7-8255-89e9794d677f.png)

![image](https://user-images.githubusercontent.com/11463809/32907058-209081d8-caff-11e7-8930-c2e09458e552.png)

Nach dem Löschen des neuen Datenpunkts sieht die Tabelle in der Adapter-Config weiterhin so aus.

**Comment by GermanBluefox** [comment]
Was ist ID und was ist der Name von diesem Objekt?

16 нояб. 2017 г. 18:51 пользователь "Michael" <notifications@github.com>
написал:

**Comment by GermanBluefox** [comment]
@ruhr70  ??
Was ist ID und was ist der Name von diesem Objekt?

**Comment by modmax** [comment]
Ist wohl mit #40 und #42 gefixt.
Mit der aktuellen Version besteht keion Problem mehr und kann daher als gelöst betrachtet werden.
