### ISSUE TITLE
Upgrade jarvis v2 to v3

### ISSUE THREAD

**Issue by Zefau** [ioBroker/ioBroker.cloud#290]
Please upgrade ioBroker.jarvis in the cloud from v2 to v3.0.11

**Comment by Zefau** [comment]
https://github.com/ioBroker/ioBroker.cloud/issues/269

**Comment by Zefau** [comment]
@GermanBluefox do you roughly know when you have the chance to update?

**Comment by SKB-CGN** [comment]
Please Update this.

Thanks

**Comment by masterplan89** [comment]
Update please. Best vis ever

**Comment by GermanBluefox** [comment]
That is very strange, as the `iobroker.jarvis` does not cached in the cloud. May be clean local cache will help?

**Comment by cbroeker1224** [comment]
When trying to open jarvis through the cloud (iobroker.pro) i get this error in my iobroker log:
cloud.0 | 2022-08-26 22:20:04.155 | error | Cannot request web pages: File index.html not found: {}

**Comment by ScumbagSteve** [comment]
Would be great if someone could look into this issue. Without this for me the iobroker remote license is mostly useless :(

**Comment by Apollon77** [comment]
@Zefau Bluefox tried to update Jarvis to 3.0.13 short time ago and it was no longer working because there are now absolut paths to resources used. This is not compatible to the cloud where the webpage paths have a prefix and do not start at the root like with a local web adapter.

Can you please check this and give us feedback?

**Comment by Zefau** [comment]
Wo denn konkret, bevor ich jetzt lange suche?

Vermutlich kommt es vom build Prozess. Absichtlich sind nur externe URLs fest, also z.B. von Iconify zum Laden der Icons.

**Comment by Apollon77** [comment]
@GermanBluefox Dann ggf nochmal aktualisieren und testen?

**Comment by Zefau** [comment]
@GermanBluefox lass uns hier gerne mal kurz abstimmen, was ich ggf. fixen kann, damit v3.0 bzw. v3.1 über ioBroker.pro verfügbar ist.

**Comment by uwe72** [comment]
Beim Ticket-hopping bin ich nun hier gelandet. Habe heute ein Bugticket eingestellt, da der Zugriff auf Jarvis nicht funktioniert über iobroker.pro (https://github.com/Zefau/ioBroker.jarvis/issues/2142)

**Comment by ScumbagSteve** [comment]
Ich habe mir nun wegen der Weihnachtaktion auch mal ne Fernzugriffslizenz geholt (auch wenn ich derzeit noch nichts damit anfangen kann). Würde mich für Tests zur Verfügung stellen, falls es Bedarf gibt.
@GermanBluefox @Zefau

**Comment by Domster91** [comment]
Ich wäre auch sehr dankbar wenn ich meine Vis mit v3 unterwegs benutzen könnte über v2 ging das tadellos für mich.

**Comment by ScumbagSteve** [comment]
Ich pushe das hier nochmal.
Hoffe ein Push im Monat ist nicht zu unhöflich, aber es wäre schon ein großer Mehrwert für die aus meiner Sicht effizienteste Visualisierung für ioBroker.

**Comment by ScumbagSteve** [comment]
Das Problem besteht weiterhin und ich habe immer noch großen Bedarf an einer Lösung.

**Comment by ScumbagSteve** [comment]
Any updates / plans to fix?
I helped myself out with setting up VPN, but I have no use of the cloud license any longer if this won't be fixed.

**Comment by ScumbagSteve** [comment]
Gibt es noch Pläne das zu fixen? Ich werde dieses Jahr zur Weihnachtsaktion nicht nochmal eine Lizenz kaufen. Die Lizenz letztes Jahr war eigentlich komplett nutzlos, weil der Bug hier nie gefixt wurde. 

Wenn Jarvis irgendwann über die cloud verwendbar ist, kaufe ich gerne wieder eine.

**Comment by ScumbagSteve** [comment]
@Apollon77 @Zefau 
Könnt ihr euch hier bitte mal kurzschließen? Für vis-2 gab es jetzt ein Update und Jarvis funktioniert seit fast 2 Jahren nicht mehr 😕

**Comment by Apollon77** [comment]
AM besten @Zefau schreibt mal Denis unter info@iobroker.net an, dann können die zwei sich da abstimmen.

Generell ist es sehr schwierig zu unterstützen da GitHub alles nur "minified" enthält, damit schwierig mal eben schnell im Code zu schauen. Es sieht für mich so aus als ob Jarvis inzwischen nen eigenen Server öffnet und nicht mehr vollständig per Web läuft? ist das so? Port 8400? Wenn das so ist dann ist Cloud raus weil über Cloud keine weiteren Ports ausser Web geroutet werden können und auch nur dann wenn es Socketio/WS kompatibler traffic zu web ist...

**Comment by SKB-CGN** [comment]
> Es sieht für mich so aus als ob Jarvis inzwischen nen eigenen Server öffnet und nicht mehr vollständig per Web läuft? ist das so? Port 8400? Wenn das so ist dann ist Cloud raus weil über Cloud keine weiteren Ports ausser Web geroutet werden können und web auch nur dann wenn es Socketio/WS kompatibler traffic zu web ist...

Soweit ich das sehe, öffnet Jarvis einen eigenen Websocket Server. Richtig!
