### ISSUE TITLE
Port for external call

### ISSUE THREAD

**Issue by thomasklein1975** [ioBroker/ioBroker.cloud#300]
It is more a question then a feature request.

Which default port is used for such a call:
`https://service.iobroker.in/v1/iotService?service=custom_koha_temp&key=...&data=11 `

Background: I need a port for sending this url from a esp easy rule by usage of "SendToHTTP"

I tried http --> 8081 and https --> 8082 but with no impact.

Thx in advance
Thomas

**Comment by Apollon77** [comment]
protocol https without a defined port defaults to 443

**Comment by Apollon77** [comment]
PS: But one important question: Is the ESP easy device externally to your network? Because this endpoint is the iobroker cloud service! Whats exactly your use case?

**Comment by thomasklein1975** [comment]
thx for fast response. 
LAN/WLAN A: iobroker where data can be set by usage of iot services and given link.
LAN/WLAN B: wemos with esp easy/tasmota should send data to iobroker

**Comment by Apollon77** [comment]
ANd LAN/WLAN A can not talk to LAN/WLAN B directly?

**Comment by thomasklein1975** [comment]
B has to send to A and there is no VPN. Two different location with dsl and glasfaser. If not needed dyn dns should not be used. I would like to use iobroker cloudservice url like in my custom skill at voiceflow eg

**Comment by Apollon77** [comment]
Yes browser might ignore the fact that you mix stuff. aas is only available with https by default
