### ISSUE TITLE
RequireLog is not supported by this adapter!

### ISSUE THREAD

**Issue by FlexerJR** [ioBroker/ioBroker.cloud#308]
Hallo @Apollon77 Habe heute diese Meldung im Log gefunden nach dem Update von gestern.

Ist das nicht schon gefixt?

Viele Grüße

<html>
<body>

web.0 | 2022-05-20 08:35:50.781 | warn | requireLog is not supported by this adapter! Please set common.logTransporter to true
-- | -- | -- | --

</body>
</html>

**Comment by m0rph2k** [comment]
Kann ich bestätigen kommt bei mir auch seit kurzen 1-2 Tage

**Comment by liv-in-sky** [comment]
bei mir auch

**Comment by WolfgangGr** [comment]
Ich habe die selbe Warnung "requireLog is not supported by this adapter! Please set common.logTransporter to true".

**Comment by tmycgn** [comment]
Ebenso hier! :)

**Comment by Menne01** [comment]
Auch nach den heutigen Aktualisierungen noch immer die gleiche Warnung.

"requireLog is not supported by this adapter! Please set common.logTransporter to true"

**Comment by dreamerxch** [comment]
Jup, auch bei mir, heute zum ersten Mal aufgetreten

**Comment by GermanBluefox** [comment]
Das ist doch web.0 Meldung und nicht iobroker.cloud
