### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by Manolo68** [ioBroker/ioBroker.cloud#317]
Beim Öffnen der Konfiguration vom ioBroker.Cloud Adapter kommt Fehler "Error in GUI!

![Screenshot 2022-08-04 095512](https://user-images.githubusercontent.com/87265685/182833433-dc1a6833-c75c-4461-82c8-cd362f018a2a.png)

Dies passiert aber nur mit der neuen Benutzeroberfläche.
Bei der alten Benutzeroberfläche gibt es keine Probleme.

**Comment by Manolo68** [comment]
Das Problem konnte nach einer Neuistallation behoben werden.
Jedoch kann nun kein Whitelist Service angelegt werden.
Weder mit <Name> noch mit custom_<Name>.
Beim Versuch den cloud Adapter neu zu starten kommt folgende Fehlermeldung.

Error: TypeError: (adapter.config.allowedServices || "").split is not a function

Dieser Fehler bleibt auch nach dem Löschen der Whitelist Einträge.
Der Adapter bleibt gelb.

Beim Anlegen eines Whitelist Service unter der alten Benutzeroberfläche gibt es damit keine Probleme.

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.cloud/issues/319
