### ISSUE TITLE
Bug mit Hue Strip

### ISSUE THREAD

**Issue by Omega236** [ioBroker/ioBroker.cloud#33]
Ich habe einen Hue-Adapter in IOBroker eingebunden und dann versucht einen LED Strip im Cloud-Adapter hinzuzufügen. das hat aber nicht korrekt geklappt (im Adapter passt die Anzeige nicht -> Delete/edit fehlt und adapter beendet sich wenn man das Hue Gerät steuern will) und ich weiß nicht wie ich es aus dem Cloud-Adapter wieder entfernen

![bug hue](https://user-images.githubusercontent.com/25373047/34456451-d4e8ebac-ed96-11e7-9e6f-c1f9987dc107.PNG)
Logs:

host.homebridge | 2017-12-30 19:15:48.506 | info | object change system.adapter.cloud.0
-- | -- | -- | --
host.homebridge | 2017-12-30 19:15:36.519 | info | Restart adapter system.adapter.cloud.0 because enabled
host.homebridge | 2017-12-30 19:15:36.518 | error | instance system.adapter.cloud.0 terminated with code 0 (OK)
Caught | 2017-12-30 19:15:36.517 | error | by controller[0]:     at Decoder. (/opt/iobroker/node_modules/iobroker.cloud/node_modules/component-bind/index.js:21:15)
Caught | 2017-12-30 19:15:36.517 | error | by controller[0]:     at Manager.ondecoded  (/opt/iobroker/node_modules/iobroker.cloud/node_modules/socket.io-client/lib/manager.js:332:8)
Caught | 2017-12-30 19:15:36.516 | error | by controller[0]:     at Manager.Emitter.emit  (/opt/iobroker/node_modules/iobroker.cloud/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
Caught | 2017-12-30 19:15:36.516 | error | by controller[0]:     at Manager. (/opt/iobroker/node_modules/iobroker.cloud/node_modules/component-bind/index.js:21:15)
Caught | 2017-12-30 19:15:36.515 | error | by controller[0]:     at Socket.onpacket  (/opt/iobroker/node_modules/iobroker.cloud/node_modules/socket.io-client/lib/socket.js:228:12)
Caught | 2017-12-30 19:15:36.515 | error | by controller[0]:     at Socket.onevent  (/opt/iobroker/node_modules/iobroker.cloud/node_modules/socket.io-client/lib/socket.js:270:10)
Caught | 2017-12-30 19:15:36.514 | error | by controller[0]:     at Socket.Emitter.emit  (/opt/iobroker/node_modules/iobroker.cloud/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
Caught | 2017-12-30 19:15:36.513 | error | by controller[0]:     at Socket. (/opt/iobroker/node_modules/iobroker.cloud/main.js:540:22)
Caught | 2017-12-30 19:15:36.513 | error | by controller[0]:     at AlexaSH2.process (/opt/iobroker/node_modules/iobroker.cloud/lib/alexaSmartHomeV2.js:904:28)
Caught | 2017-12-30 19:15:36.512 | error | by controller[0]:     at Object.parse (native)
Caught | 2017-12-30 19:15:36.510 | error | by controller[0]: SyntaxError: Unexpected token h in JSON at position 0
cloud.0 | 2017-12-30 19:15:36.408 | info | terminating
cloud.0 | 2017-12-30 19:15:36.366 | info | Connection changed: DISCONNECTED3
cloud.0 | 2017-12-30 19:15:36.350 | error | at Decoder. (/opt/iobroker/node_modules/iobroker.cloud/node_modules/component-bind/index.js:21:15)
cloud.0 | 2017-12-30 19:15:36.350 | error | at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.cloud/node_modules/socket.io-client/lib/manager.js:332:8)
cloud.0 | 2017-12-30 19:15:36.350 | error | at Manager.Emitter.emit  (/opt/iobroker/node_modules/iobroker.cloud/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
cloud.0 | 2017-12-30 19:15:36.350 | error | at Manager. (/opt/iobroker/node_modules/iobroker.cloud/node_modules/component-bind/index.js:21:15)
cloud.0 | 2017-12-30 19:15:36.350 | error | at Socket.onpacket (/opt/iobroker/node_modules/iobroker.cloud/node_modules/socket.io-client/lib/socket.js:228:12)
cloud.0 | 2017-12-30 19:15:36.350 | error | at Socket.onevent (/opt/iobroker/node_modules/iobroker.cloud/node_modules/socket.io-client/lib/socket.js:270:10)
cloud.0 | 2017-12-30 19:15:36.350 | error | at Socket.Emitter.emit  (/opt/iobroker/node_modules/iobroker.cloud/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
cloud.0 | 2017-12-30 19:15:36.350 | error | at Socket. (/opt/iobroker/node_modules/iobroker.cloud/main.js:540:22)
cloud.0 | 2017-12-30 19:15:36.350 | error | at AlexaSH2.process (/opt/iobroker/node_modules/iobroker.cloud/lib/alexaSmartHomeV2.js:904:28)
cloud.0 | 2017-12-30 19:15:36.350 | error | at Object.parse (native)
cloud.0 | 2017-12-30 19:15:36.350 | error | SyntaxError: Unexpected token h in JSON at position 0
cloud.0 | 2017-12-30 19:15:36.348 | error | uncaught exception: Unexpected token h in JSON at position 0
cloud.0 | 2017-12-30 19:15:14.089 | info | Connection changed: CONNECTED1
cloud.0 | 2017-12-30 19:15:13.495 | info | 2017-12-30T18:15:13.493Z Connected system.user.admin

**Comment by modmax** [comment]
Ist das gleiche Problem wie in #29 beschrieben.
Dies ist mit der neuesten Version aus #40 bzw. #42 behoben.

Für ältere Versionen gibt es den Workaround, daß man beim Datenpunkt "hue" der entsprechend Hue-Lampe den SmartName auf false setzt, oder den ganzen custom, oder cloud.0-Teil aus dem Datenpunkt über die raw-Ansicht des Objekts entfernt.
