### ISSUE TITLE
ioBroker.pro Cloud Verbindungsabbrüche

### ISSUE THREAD

**Issue by KL1801** [ioBroker/ioBroker.cloud#331]
Hallo,

Wie in diesem Thema beschrieben https://forum.iobroker.net/topic/58412/pro-cloud-update-mit-admin-6-problem-meldungen/24?_=1666263737790 stürzt die Cloud öfters ab.

Wenn ich irgendetwas mache, sei es in der Visualisierung oder sonst wo, wird mit mal angezeigt "ioBroker not connected". Wenn ich dann [iobroker.pro](http://iobroker.pro/) neu lade erscheint der ladebalken. Manchmal nach ein paar Sekunden, manchmal auch erst nach ein paar Minuten, funktioniert die Verbindung wieder.
Woran kann das liegen?

Das ganze sieht dann so aus:
![grafik](https://user-images.githubusercontent.com/18719162/197113867-253f0a58-c33f-4dfb-9035-8cdbcd837984.png)

Viele Grüße!

**Comment by KL1801** [comment]
Ich glaube den Fehler gefunden zu haben...
Ich hatte mich mit den pro-Login-Daten in den Cloud-Adaptereinstellungen eingewählt. Seit ich das geändert habe in "Appkey" ist die Cloud noch nicht wieder abgebrochen :)

**Comment by KL1801** [comment]
Leider zu früh gefreut... Gestern ging die Cloud den ganzen Tag ohne Verbindungsabbrüche. Heute morgen ein wenig über die Cloud am iobroker gearbeitet, und leider wieder einige Verbindungsabbrüche gehabt...

**Comment by KL1801** [comment]
Guten Morgen,

Leider auch wieder zu früh gefreut. Selbst mit dem Google Chrome Browser stürtzt die Cloud - am heutigen morgen sogar nahezu sekündlich - ständig ab.
"ioBroker not connected" und die Ladeoberfläche wie oben im Bild gezeigt stehen heute Morgen fast ununterbrochen auf dem Programm...

**Comment by KL1801** [comment]
Nun ging es wieder eine Zeit lang gut, bis jetzt allerdings wieder ständig die Cloudverbindung abbricht.
Ich habe mal noch ein Screenshot des Chrome-Entwicklungstools mit dem jeweiligen Fehler angehangen. Scheint etwas ausführlicher als bei Firefox zu sein:

![grafik](https://user-images.githubusercontent.com/18719162/198228936-0339e35f-e3c5-4e13-a29a-9a45f4db0b8f.png)

**Comment by KL1801** [comment]
Bin einem Fehler damals auf die Schliche gekommen: Der Adapter "daswetter" hat Probleme gemacht, danach ist dann jedes mal die Cloud abgesützt (Cloud says: Too many updates or requests, Sending to many events. Account is blocked for 5 minutes. Please restart cloud adapter.)... Nachdem ich den Adapter deaktiviert hatte, funktionierte es.

Nun aber habe ich WIEDER CLOUD ABBRÜCHE!!

Ich habe den Cloud Adapter im Debug stehen und habe das Log einmal angehangen.

Es wäre schön, Hilfe zu bekommen!
[Cloud_Debug_Log.txt](https://github.com/ioBroker/ioBroker.cloud/files/10131750/Cloud_Debug_Log.txt)

Ihr müsst die Datei .txt in .htm umbenennen... HTML Dateien kann ich hier leider nicht anhängen...

**Comment by Apollon77** [comment]
Hm ... ok das Log ist an sich eindeutig. Irgendein Adapter generiert sehr viele Daten und du hast den Teil des baums scheinbar im Cloud Admin aufgeklappt. Das ist das problem

**Comment by Apollon77** [comment]
Zuklappen: ja. Admin subscribed immer die states die sichtbar sind quasi ... Also wenn zuviel offen ist kann es auch diesen block geben. ALso zb Baum ganz aufklappen wird denke in cloud nie gescheit gehen. Vllt ists ja nur sowas und gar nicht "eine instanz" die spammt.

Unter Instanzen mit dem expertenmodus gibt es infos wieviele States geschrieben bzw subscribed sind pro Instanz ... da mal schauen

**Comment by KL1801** [comment]
> 

Guten morgen!

Ich habe den Baum gestern nach Deiner Nachricht geschlossen. Wie ich gerade festgestellt habe, hat das aber keinen Mehrwert gebracht.

Lässt sich hieraus etwas erkennen? (Sorry, immer noch kein Profi :/ )

![grafik](https://user-images.githubusercontent.com/18719162/205214446-182e9cf4-e157-4884-8289-69266abf4700.png)

![grafik](https://user-images.githubusercontent.com/18719162/205214500-ffd93ba3-976d-4f1f-9633-c91fdb7e1968.png)

![grafik](https://user-images.githubusercontent.com/18719162/205214570-609e2e12-03e7-4128-8177-e3da65ae8b90.png)

**Comment by SmartHomer0** [comment]
Ich habe leider das selbe Problem - wenn ich über ioBroker pro eingeloggt bin, steht die Verbindung nur für wenige Senkunden, max. eine Minute, dann kommt "is not connected".
Das Ganze unabhängig davon, ob die Objekteliste im Hintergrund zu- oder aufgeklappt ist.

**Comment by Apollon77** [comment]
Steht irgendwas im Log vom Browser bzw auf server seite?

**Comment by SmartHomer0** [comment]
Letztlich kommt es eben immer wieder zum Problem "_Failed to load resource: the server responded with a status of 404 (Not Found)_"

Hilft Dir dieser Auszug aus dem Protokoll des Edge-Browser evtl. weiter (das Problem tritt jedoch unter FireFox ebenso auf):

`Create inner vis object froeling.0.46918.componentList.Austragung-Austragung.topView.pictureUrl
vis.js:3543 Create inner vis object 0_userdata.0.Variablen.Geb_Tasten-LED-OG_(Blockly)
VM1072:140 Version vis-canvas-gauges: 0.1.5
VM1076:402 Version eventlist: 1.0.1
VM1082:115 Version justgage: 1.0.2
VM1085:110 Version vis-jqui-mfd: 1.0.12
VM1087:645 Metro version: "1.2.0"
VM1092:21 Version Info-Adapter-Widget: 0.0.9
vis.js:447 
        
       Cannot load widget set "materialdesign": ReferenceError: myMdwHelper is not defined
(anonym) @ vis.js:447
VM1104:97 Version vis-plumb: 1.0.0
VM1112:152 Version trashschedule: 2.0.3
VM1137:184 Version vis-material-advanced: 1.7.3
VM1095:43 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
VM1095:43 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
VM1111:127 Version vis-timeandweather: 1.2.1
undefined:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
2​ Mon Dec 26 2022 13:44:58 GMT+0100 (Mitteleuropäische Normalzeit) - Tue Dec 27 2022 13:44:58 GMT+0100 (Mitteleuropäische Normalzeit)
vis.js:389 ID is null for val=undefined
translate.js:20 "Error": {"en": "Error", "de": "Error", "ru": "Error"},
jquery-1.11.2.min.js:2 
        
       Uncaught TypeError: Cannot read properties of null (reading 'length')
    at Function.each (jquery-1.11.2.min.js:2:2821)
    at Object.redraw (eval at <anonymous> (VM1232 jquery-1.11.2.min.js:2:2622), <anonymous>:343:15)
    at Object.createWidget (eval at <anonymous> (VM1232 jquery-1.11.2.min.js:2:2622), <anonymous>:181:36)
    at eval (eval at <anonymous> (VM1232 jquery-1.11.2.min.js:2:2622), <anonymous>:161:44)
each @ jquery-1.11.2.min.js:2
redraw @ VM1112:343
createWidget @ VM1112:181
eval @ VM1112:161
VM1238 flot.js:1 Mon Dec 26 2022 13:46:30 GMT+0100 (Mitteleuropäische Normalzeit) - Tue Dec 27 2022 13:46:30 GMT+0100 (Mitteleuropäische Normalzeit)
VM1238 flot.js:1 
        
       ioBroker is not connected
(anonym) @ VM1238 flot.js:1
VM1238 flot.js:1 Mon Dec 26 2022 13:46:30 GMT+0100 (Mitteleuropäische Normalzeit) - Tue Dec 27 2022 13:46:30 GMT+0100 (Mitteleuropäische Normalzeit)
VM1238 flot.js:1 
        
       ioBroker is not connected
(anonym) @ VM1238 flot.js:1
VM1238 flot.js:1 
        
       Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at VM1238 flot.js:1:72243
    at new CustomChart (VM1238 flot.js:1:78601)
    at prepareChart (VM1238 flot.js:1:87389)
    at VM1238 flot.js:1:91690
    at readMarkings (VM1238 flot.js:1:90047)
    at VM1238 flot.js:1:91592
    at readTicks (VM1238 flot.js:1:89944)
    at VM1238 flot.js:1:91570
    at _readData (VM1238 flot.js:1:91072)
    at VM1238 flot.js:1:91184
VM1322 flot.js:1 Mon Dec 26 2022 13:47:38 GMT+0100 (Mitteleuropäische Normalzeit) - Tue Dec 27 2022 13:47:38 GMT+0100 (Mitteleuropäische Normalzeit)
VM1322 flot.js:1 
        
       ioBroker is not connected
(anonym) @ VM1322 flot.js:1
n.onack @ VM1324 socket.io.js:3
n.onpacket @ VM1324 socket.io.js:3
(anonym) @ VM1324 socket.io.js:3
n.emit @ VM1324 socket.io.js:2
n.ondecoded @ VM1324 socket.io.js:1
(anonym) @ VM1324 socket.io.js:3
r.emit @ VM1324 socket.io.js:1
s.add @ VM1324 socket.io.js:1
n.ondata @ VM1324 socket.io.js:1
(anonym) @ VM1324 socket.io.js:3
n.emit @ VM1324 socket.io.js:2
n.onPacket @ VM1324 socket.io.js:2
(anonym) @ VM1324 socket.io.js:2
n.emit @ VM1324 socket.io.js:2
n.onPacket @ VM1324 socket.io.js:2
n.onData @ VM1324 socket.io.js:2
ws.onmessage @ VM1324 socket.io.js:3
VM1322 flot.js:1 Mon Dec 26 2022 13:47:38 GMT+0100 (Mitteleuropäische Normalzeit) - Tue Dec 27 2022 13:47:38 GMT+0100 (Mitteleuropäische Normalzeit)
VM1322 flot.js:1 
        
       ioBroker is not connected
(anonym) @ VM1322 flot.js:1
n.onack @ VM1324 socket.io.js:3
n.onpacket @ VM1324 socket.io.js:3
(anonym) @ VM1324 socket.io.js:3
n.emit @ VM1324 socket.io.js:2
n.ondecoded @ VM1324 socket.io.js:1
(anonym) @ VM1324 socket.io.js:3
r.emit @ VM1324 socket.io.js:1
s.add @ VM1324 socket.io.js:1
n.ondata @ VM1324 socket.io.js:1
(anonym) @ VM1324 socket.io.js:3
n.emit @ VM1324 socket.io.js:2
n.onPacket @ VM1324 socket.io.js:2
(anonym) @ VM1324 socket.io.js:2
n.emit @ VM1324 socket.io.js:2
n.onPacket @ VM1324 socket.io.js:2
n.onData @ VM1324 socket.io.js:2
ws.onmessage @ VM1324 socket.io.js:3
VM1322 flot.js:1 
        
       Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at VM1322 flot.js:1:72243
    at new CustomChart (VM1322 flot.js:1:78601)
    at prepareChart (VM1322 flot.js:1:87389)
    at VM1322 flot.js:1:91690
    at readMarkings (VM1322 flot.js:1:90047)
    at VM1322 flot.js:1:91592
    at readTicks (VM1322 flot.js:1:89944)
    at VM1322 flot.js:1:91570
    at _readData (VM1322 flot.js:1:91072)
    at VM1322 flot.js:1:91184
(anonym) @ VM1322 flot.js:1
CustomChart @ VM1322 flot.js:1
prepareChart @ VM1322 flot.js:1
(anonym) @ VM1322 flot.js:1
readMarkings @ VM1322 flot.js:1
(anonym) @ VM1322 flot.js:1
readTicks @ VM1322 flot.js:1
(anonym) @ VM1322 flot.js:1
_readData @ VM1322 flot.js:1
(anonym) @ VM1322 flot.js:1
setTimeout (asynchron)
(anonym) @ VM1322 flot.js:1
(anonym) @ VM1322 flot.js:1
n.onack @ VM1324 socket.io.js:3
n.onpacket @ VM1324 socket.io.js:3
(anonym) @ VM1324 socket.io.js:3
n.emit @ VM1324 socket.io.js:2
n.ondecoded @ VM1324 socket.io.js:1
(anonym) @ VM1324 socket.io.js:3
r.emit @ VM1324 socket.io.js:1
s.add @ VM1324 socket.io.js:1
n.ondata @ VM1324 socket.io.js:1
(anonym) @ VM1324 socket.io.js:3
n.emit @ VM1324 socket.io.js:2
n.onPacket @ VM1324 socket.io.js:2
(anonym) @ VM1324 socket.io.js:2
n.emit @ VM1324 socket.io.js:2
n.onPacket @ VM1324 socket.io.js:2
n.onData @ VM1324 socket.io.js:2
ws.onmessage @ VM1324 socket.io.js:3
data.js:429 Mon Dec 26 2022 13:50:18 GMT+0100 (Mitteleuropäische Normalzeit) - Tue Dec 27 2022 13:50:18 GMT+0100 (Mitteleuropäische Normalzeit)
data.js:431 
        
       ioBroker is not connected
(anonym) @ data.js:431
n.onack @ socket.io.js:3
n.onpacket @ socket.io.js:3
(anonym) @ socket.io.js:3
n.emit @ socket.io.js:2
n.ondecoded @ socket.io.js:1
(anonym) @ socket.io.js:3
r.emit @ socket.io.js:1
s.add @ socket.io.js:1
n.ondata @ socket.io.js:1
(anonym) @ socket.io.js:3
n.emit @ socket.io.js:2
n.onPacket @ socket.io.js:2
(anonym) @ socket.io.js:2
n.emit @ socket.io.js:2
n.onPacket @ socket.io.js:2
n.onData @ socket.io.js:2
ws.onmessage @ socket.io.js:3
data.js:429 Mon Dec 26 2022 13:50:18 GMT+0100 (Mitteleuropäische Normalzeit) - Tue Dec 27 2022 13:50:18 GMT+0100 (Mitteleuropäische Normalzeit)`

**Comment by Apollon77** [comment]
Also die "404" Fehlr, vor allem bei .map Dateien sind einfach zu ignorieren. Da sist egal weil unnötig. Ebenso 404s bei Bildern oder sowas.

Die type errors sind eher interessant. 

Wir sollten auch nochmal klar stellen ob es um Visualisierungen per Por cloud geht oder Admin? Vier hissts eher "vis"? Korrekt? Oder der Vis editor? Details bitte dazu

**Comment by SmartHomer0** [comment]
Ich habe folgendes gemacht:

- Browser aufgerufen
- www.iobroker.pro
- Anmeldung mit meinen Anmeldedaten
- Anwendungen
- Vis Editor
- Auswahl meines Vis-Projekts
- Vis Runtime
und dann tritt der Fehler während der Runtime auf.

Zum Vergleich:
Wenn ich das selbe wie bisher über einen VPN mache (statt des ioBroker Remote Access), läuft alles auch über einen längeren Zeitraum prima.

Ich hoffe, ich habe Deine Frage richtig verstanden

**Comment by SmartHomer0** [comment]
Das Problem mit dem "is not connected" kommt manchmal auch schon beim Aufruf/Laden des Editors oder auch wenn ich statt dem Editor den Admin aufrufe - also eigentlich bei jedem Zugriff über den Menuepunkt "Anwendungen" aus ioBroker.pro

**Comment by scramer75** [comment]
Ich habe leider die gleichen Probleme. Extern über den Pro habe ich alle paar Sekunden Verbindungsabbrüche und Neustarts.
So lohnt sich der Pro Account auf jeden Fall mal gar nicht  :-(

Hier die cloud.0 Meldungen dazu:


cloud.0 | 2023-02-07 00:06:26.870 | info | User disconnected from cloud: ojshT9VBpXZI7x_LACl8
-- | -- | -- | --
cloud.0 | 2023-02-07 00:05:45.368 | info | User disconnected from cloud: J4JjUp6hG65nHXN6AClP
cloud.0 | 2023-02-07 00:05:12.820 | info | received all objects
cloud.0 | 2023-02-07 00:05:05.925 | info | User disconnected from cloud: tgqRx0lZCCsem-qrAClM
cloud.0 | 2023-02-07 00:05:05.012 | info | User accessed from cloud: ASR0xcttE0hhyJAbACl-
cloud.0 | 2023-02-07 00:05:01.662 | info | User accessed from cloud: ojshT9VBpXZI7x_LACl8
cloud.0 | 2023-02-07 00:04:18.467 | info | User disconnected from cloud: XWcKDVQmVZ3v6NQwACki
cloud.0 | 2023-02-07 00:04:08.600 | info | received all objects
cloud.0 | 2023-02-07 00:03:46.164 | info | User accessed from cloud: J4JjUp6hG65nHXN6AClP
cloud.0 | 2023-02-07 00:03:40.958 | info | User accessed from cloud: tgqRx0lZCCsem-qrAClM
cloud.0 | 2023-02-07 00:03:11.785 | info | User disconnected from cloud: cX2m3G7xPYURM5qJACkE
cloud.0 | 2023-02-07 00:02:44.812 | info | received all objects
cloud.0 | 2023-02-07 00:02:32.328 | info | User disconnected from cloud: fxixI6xr4Bw6RqJDACkC
cloud.0 | 2023-02-07 00:02:25.745 | info | User accessed from cloud: XWcKDVQmVZ3v6NQwACki
cloud.0 | 2023-02-07 00:01:55.011 | info | User disconnected from cloud: k951T2ouDoiUgpleACjj
cloud.0 | 2023-02-07 00:01:39.782 | info | received all objects
cloud.0 | 2023-02-07 00:01:11.576 | info | User accessed from cloud: cX2m3G7xPYURM5qJACkE
cloud.0 | 2023-02-07 00:01:07.333 | info | User accessed from cloud: fxixI6xr4Bw6RqJDACkC
cloud.0 | 2023-02-07 00:00:57.271 | info | User disconnected from cloud: ggVzjLsMVk5FHv0MACjZ
cloud.0 | 2023-02-07 00:00:09.314 | info | User disconnected from cloud: n2c9nHlHiWzl13dWACjO


Andauernde An- und Abmeldungen...das könnte bei mir wohl das Problem sein. Aber warum?
