### ISSUE TITLE
Datenpunkt für Abo-Laufzeit im Cloud-Adapter

### ISSUE THREAD

**Issue by SebastianSchultz** [ioBroker/ioBroker.cloud#36]
Ich würde mir im Cloud-Adapter einen Datenpunkt wünschen, in dem die Abo-Laufzeit bzw. das Enddatum definiert ist.
Nach Möglichkeit mit Live-Daten aus dem Cloud-Account.

So kann ich mir

a.) in der VIS in meinem "Systemeinstellungs"-View das Datum anzeigen lassen
b.) mit eine Erinnerung für die Verlängerung generieren :)

**Comment by GermanBluefox** [comment]
Implemented in 2.5.0 
Cloud Server must be restarted first.

**Comment by SebastianSchultz** [comment]
Was the cloud server restarted, yet?
Cause my cloud.0.remoteTill is empty.

**Comment by Apollon77** [comment]
We should have a pro server restart tomorrow (Sunday) 23:00 for ssl certificate changes.

**Comment by SebastianSchultz** [comment]
My cloud.0.remoteTill state is still empty.
Was the server not restarted?

**Comment by Apollon77** [comment]
No It was free. Pro comes Saturday night
