### ISSUE TITLE
Error(s) when creating new smart devices

### ISSUE THREAD

**Issue by frankjoke** [ioBroker/ioBroker.cloud#37]
Dear team! (V 2.1.1)

Dear team, I wanted to exchange smart device to new WLAN from old RF plugs and needed to delete the old smart device and create new ones.

I failed and used chrome debugger to check what happens after I select the state because in most cases the next window where you can edit the name/word(s) of the smart device did never show up.

There are several bugs in the  admin/index.html of the adapter, mainly in updateSmartName.

The first is that on line 412 the statement `if (obj.native.byON) {`, the call fails automatically if the object has no native, which is the case for most objects for me.

The second is in line  449/450 `if (smartName && (!smartName[language] || (smartName[language] === obj.common.name && (!obj.common.role || obj.common.role.indexOf('button') === -1)))) {
                delete smartName[language];`
It deletes again the smartName if the role is not 'button' and the common.name same as SmartName! Most states have role 'state, switch, level, ...'  and not button and on the other side the SmartName before is generated from the common-name, just changing some special caracters.
Therefore iof no such special caracters exist in common.name and the role is not 'button' no smartname can be generated from it! This is the case for 90% of my states :(

There is a workaround for both cases how I managed to get around the bugs and enter new states into the smart list: Create a dummy native-entry and create a  
 "smartName": {
      "de": "SmartNameToUse"
    }
in common which then is different from the common.name.

My strong believe is that this should not be the case at all!

Thanks in advance to look @ this topic ASAP.

**Comment by AlCalzone** [comment]
#40 changes a bunch of stuff in the admin interface and the adapter code. Please test again with the version you can install from https://github.com/WolfspiritM/ioBroker.cloud/tarball/major-bugfixes and see if that fixes your issue.

**Comment by frankjoke** [comment]
Hi Alcazone!

I checked and can see that one Problem is resolved, but the other is still there!

The code below (line 493...) deletes all smart names and does not allow to create ones for states which are not buttons or have the same name as common.name.

This is virtually true for most states because the routine defaults to the common.name as newStateName!

I don't know what you want to chechieve with this if because in there you check there3 virtually all new ( in the lines befoe 493) created smartNames are deleted again and they are empty!

`            if (smartName && (!smartName[language] || (smartName[language] === obj.common.name && (!obj.common.role || obj.common.role.indexOf('button') === -1)))) {
                delete smartName[language];
                var empty = true;
                for (var key in smartName) {
                    if (smartName.hasOwnProperty(key)) {
                        empty = false;
                        break;
                    }
                }
                if (empty) {
                    if (noCommon) {
                        if (obj.common.custom[adapter + '.' + instance].smartName.byON === undefined) {
                            delete obj.common.custom[adapter + '.' + instance];
                        } else {
                            delete obj.common.custom[adapter + '.' + instance].en;
                            delete obj.common.custom[adapter + '.' + instance].de;
                            delete obj.common.custom[adapter + '.' + instance].ru;
                            delete obj.common.custom[adapter + '.' + instance].nl;
                            delete obj.common.custom[adapter + '.' + instance].pl;
                            delete obj.common.custom[adapter + '.' + instance].it;
                            delete obj.common.custom[adapter + '.' + instance].fr;
                        }
                    } else {
                        if (obj.common.smartName.byON !== undefined) {
                            delete obj.common.smartName.en;
                            delete obj.common.smartName.de;
                            delete obj.common.smartName.ru;
                            delete obj.common.smartName.nl;
                            delete obj.common.smartName.pl;
                            delete obj.common.smartName.it;
                            delete obj.common.smartName.fr;
                        } else {
                            obj.common.smartName = null;
                        }
                    }
                }`

**Comment by frankjoke** [comment]
I just checked again and I believe the 
`if (smartName && (!smartName[language] || (smartName[language] === obj.common.name && (!obj.common.role || obj.common.role.indexOf('button') === -1))))`

should be a `if (smartName && (!smartName[language] || (smartName[language] === obj.common.name && (!obj.common.role || obj.common.role.indexOf('button') >=0))))`

if the reason for this check is to filter out buttons. By the way, why do you want to filter them out at all?

**Comment by AlCalzone** [comment]
I didn't write the code so I'm not sure what its supposed to achieve. If you know what's necessary to fix your issue, you could create a PR on @WolfspiritM's branch https://github.com/WolfspiritM/ioBroker.cloud/tree/major-bugfixes to include your changes in the #40 PR or post in the PR thread.

**Comment by frankjoke** [comment]
I crteated a pull request called `correct 'button' check` on https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWolfspiritM%2FioBroker.cloud%2Ftree%2Fmajor-bugfixes&data=02%7C01%7C%7C16177dc49d9f4d8eb61608d55516726c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636508477254775322&sdata=ukp4iIwpXTx8RyfmxcPr9eR1KuWb8Ye0Nl4dQ%2BRoL9w%3D&reserved=0.

This works on my machine.

**Comment by WolfspiritM** [comment]
I'm a bit unsure as I can add new smartnames without problem can you explain a bit more please?
If you use the "+" from the cloud admin then a smartName is created and that should be an object and not a string (as it also contains the byON value for example). A smartName that is not an object seems to be an old syntax and is not the recommended way at all.
It's possible however that somewhere this type of smartNames are still created...if that is the case we should find that instead.

**Comment by WolfspiritM** [comment]
Okay I figured out the problem, yes. I will merge your change.
I also wonder why there is a special case for buttons...

**Comment by GermanBluefox** [comment]
Buttons cannot be controlled. They lost nothing in alexa. You must control that what controls the button.

**Comment by frankjoke** [comment]
Bluefox, Buttons can be pressed (stwitched to on) and then take an action. If I want to use Alexa to take this action I need access to the button!
The only difference is that a switch has two states whereas the button can only be triggered.

**Comment by AlCalzone** [comment]
I think with the new appliance types, e.g. SCENE_ACTIVATION (I believe), allowing buttons makes sense, doesn't it?

**Comment by GermanBluefox** [comment]
The idea is: button controls something. 
Please show me the use case. 
And what should we do with "Alexa switch the button off" ?

**Comment by AlCalzone** [comment]
> And what should we do with "Alexa switch the button off" ?

Ignore, probably.

> Please show me the use case.

I currently have none, but I could imagine triggering scenes is one of them - although those are implemented as switches. I'm not sure how the Alexa app handles SCENE_ACTIVATION devices. If you can only trigger them, that would make sense - especially if the scene only does something when turned on.
@frankjoke ?

**Comment by frankjoke** [comment]
I use some of them in my adapters. Scenes or sending information to remote controls are heavy uses for buttons. I use them already  with Alexa in that way.

I just ignore the 'turn off = set to false on the buttons!

**Comment by GermanBluefox** [comment]
Ok. who will do that? :)

**Comment by GermanBluefox** [comment]
Any news here?

**Comment by AlCalzone** [comment]
No, I forgot about it.
