### ISSUE TITLE
Added applianceType to smartNames

### ISSUE THREAD

**Issue by modmax** [ioBroker/ioBroker.cloud#39]
In order to group lights into a room along with an alexa device and say "Licht an/aus" and all lights are turned on or off an applianceType must be added to the smart name.

I investigated that following appliance types are possible:
* CAMERA
* LIGHT 
* SMARTLOCK
* SMARTPLUG
* SWITCH	
* THERMOSTAT
* ACTIVITY_TRIGGER (for grouped smart names???)
* SCENE_TRIGGER 

See also:
http://forum.iobroker.net/viewtopic.php?f=37&t=10202

**Comment by Baenker** [comment]
with the actual version from wolfspiritm its possible to define the types.

Look in the thread.

It works great for me...

**Comment by modmax** [comment]
Solved with #40.
