### ISSUE TITLE
ioBroker.hm-rega restart/update causes to reset all smart bindings

### ISSUE THREAD

**Issue by jens-maus** [ioBroker/ioBroker.cloud#4]
if the hm-rega adapter is updating its enums or the adapter is restarted, this causes the "Smart Bindings" for Rooms and Gewerke to be reset, thus all entries are reselected even if the user deselected all entries previously. This results in all combinations to be regenerated and thus Alexa updates itself to know more devices even though the user didn't want that.

**Comment by jens-maus** [comment]
The problem seem to be solved after having updated js-controller to version 0.15.1. However, this js-controller version is still not available on npm, thus I didn't recognise  that this version fixes the problem with the cloud adapter. So please update the npm version accordingly.

**Comment by GermanBluefox** [comment]
Problem was solved not in js-controller but in hm-rega.
https://github.com/ioBroker/ioBroker.hm-rega/commit/ac6f2817db64cad58188d79747e5a114ab2bbce1

**Comment by GermanBluefox** [comment]
and if it works, I can publish hm-rega and close the issue :)

**Comment by jens-maus** [comment]
yes, it seems to work.
