### ISSUE TITLE
der Cloud adapter startet nicht mehr

### ISSUE THREAD

**Issue by eXplOiD1** [ioBroker/ioBroker.cloud#41]
seit kurzem startet der adapter nicht mehr als fehler bekomme ich nur

cloud.0 | 2018-01-05 20:40:26.932 | error | Error while connecting to cloud: Error: xhr poll error
-- | -- | -- | --
cloud.0 | 2018-01-05 20:40:16.906 | error | Error while connecting to cloud: Error: xhr poll error
cloud.0 | 2018-01-05 20:40:06.876 | error | Error while connecting to cloud: Error: xhr poll error

**Comment by Apollon77** [comment]
Wartungsarbeiten am Server. Siehe forum
