### ISSUE TITLE
Cannot set same name for different datapoint via cloud adapter

### ISSUE THREAD

**Issue by modmax** [ioBroker/ioBroker.cloud#44]
Within the cloud adapter it was possible to set 2 datapoints and then give them the same name.
So bot datapounts were grouped into one name.

With the latest version from github this is not possible anymore. An error message occurs with says,
that the name is already present. No merge of 2 datapoints into one name could be done via cloud adapter.

Workaround for this is to edit the custom section of each datapoint within the object view.

**Comment by Baenker** [comment]
in previois version it wasn‘t in my installation possible to group into one name. Only in raw-mode see 

http://www.iobroker.net/docu/?page_id=5910&lang=de

**Comment by modmax** [comment]
I had never an issue with setting the same name for 2 datapoints.

In my actual cas the 2 states "level" and "on" for the same devices.

I also changed the custom part of the object and then it worked. But due it worked in previous version it could be, that the newest fixed have changed something in that behaviour.

**Comment by modmax** [comment]
Okay: I've tested again for a hue lamp.

In the cloud adapter:
1.) Add "on" for "HueLampe" with name "Test" --> ok
2.) Add "level" for "HueLampe" with name "Test" -->Error, cause duplicate name
3.) Changed the smart name for object HueLampe.level from "HueLampe level" to "Test" --> ok
Now both data points are group into "Test".

Now add "HueLampe.ct" with smartName "Test" --> ok
And now on,level and ct are groupd into Test.

Thsi behaviour is reproducable.
If you add a second state to an already existing state with the same name then an erroc occurs.
But if 2 (or more states) are already grouped, then no error occurs, when another state with same smart name is added to the group.
So I think wghen adding a state with defined smart name, then a check for "single state" or "group" will be done. Perhaps this differentation could be eliminated.

**Comment by AlCalzone** [comment]
For me it always has been like that. You have to add a comma at the end of the name, e.g. "Test," then no error occurs and the devices are grouped. But since that is pretty dumb, I'd be fine with dropping that duplicate check.
