### ISSUE TITLE
daily restart

### ISSUE THREAD

**Issue by Goersch** [ioBroker/ioBroker.cloud#5]
would be nice to be able to parametrize (from within the setup mask) the time when the adapter restarts itself (right now it is 4am but I would like to shift it to 5am).

**Comment by GermanBluefox** [comment]
You can set it on second tab (Instances)  in admin in expert mode.

17 Янв 2017 г. 16:59 пользователь "Goersch" <notifications@github.com>
написал:

**Comment by Goersch** [comment]
ah, ok - found it - thanks :)
