### ISSUE TITLE
Admin/Skripte wird nicht geladen

### ISSUE THREAD

**Issue by andybali** [ioBroker/ioBroker.cloud#51]
Zugriff auf die Skripte bleibt bei "Verarbeite..." hängen und wird nicht geladen.
![2018-01-15 09_57_28-iobroker admin](https://user-images.githubusercontent.com/26953186/34934367-8a39e5de-f9da-11e7-88b9-d6cb473f3b1f.jpg)

**Comment by GermanBluefox** [comment]
Fixed.

**Comment by andybali** [comment]
Also bei mir geht es immer noch nicht!?
