### ISSUE TITLE
Smart Geräte hinzufügen

### ISSUE THREAD

**Issue by xDarix** [ioBroker/ioBroker.cloud#58]
Der Button "Gerät hinzufügen" hat keine funktion

**Comment by Stephant1** [comment]
Es können keine Geräte zugefügt werden

**Comment by amico1** [comment]
"Gerät hinzufügen" (+ Knopf ) funktioniert nicht

**Comment by ichichich3011** [comment]
Klick auf „Gerät hinzufügen“ ohne Auswirkung.

**Comment by pergo777** [comment]
Der Button "Gerät hinzufügen" hat keine funktion

**Comment by EnerGiehl** [comment]
Der Button "Gerät hinzufügen" hat keine funktion

**Comment by pfleiderer** [comment]
die neueste Version des cloud adapter (2.4.5) über Git istallieren dann geht das hinzufügen zum cloud adapter. 
Admin v3 neueste version vorausgesetzt

**Comment by werner256** [comment]
Ich habe die Version 2.4.5 installiert, aber wenn ich das "+" drücke passiert nichts (außer dass die "Adapterkonfiguration" abgedunkelt wird).

**Comment by Ichda** [comment]
Ich habe auch Cloud 2.4.5 installiert und außer ein abdunkeln funktioniert der + Button nicht. Vorher tat sich gar nichts. Habe aktuelle Chrome und Firefox Browser probiert. Installation von admin 3.1.10.

**Comment by eumats** [comment]
Leider muss ich mich hier anschließen. Beim betätigen von + kommt der graue Hintergrund und nix passiert. Firefox, Safari und leeren des Caches beider Browser hat nix gebracht. Auch ein Neustart des PI3 nicht..

**Comment by amico1** [comment]
Bei mir geht´s jetzt mit Version 2.4.5 unter Admin 3.1.10. Nutze Chrome unter Windows 10.

**Comment by werner256** [comment]
Bei mir geht's noch immer nicht. zu allem Überfluss sind seit heute alle Smart Geräte bei Alexa Offline!?

**Comment by palbiez** [comment]
Ihr müsst die Version 2.4.5 runterladen und installieren über das manuelle Update. Oder über die Console auf eurem Server. :-) 
Safari auf mehreren Systemen funktioniert damit wunderbar.

**Comment by werner256** [comment]
![unbenannt](https://user-images.githubusercontent.com/36113944/35781816-48a533ba-09ef-11e8-8c22-75b22c9a253c.PNG)
Safari will ich mir jetzt nicht extra installieren...

**Comment by werner256** [comment]
Nervig. Habe jetzt Backup von vor 14 Tagen eingespielt und alles geht wieder, vor allen Dingen funktioniert die Steuerung über Alexa wieder. Admin 2.0.9, Cloud 2.1.1
Wie gibt's sowas?

**Comment by Ilovegym66** [comment]
Hallo, 
bei mir funktioniert das hinzufuegen von Geraeten nur bedingt, ich kann manche Objekte hinzufuegen, manche garnicht. Wenn es geht, dann wird nach bestaetigen des Objekts das Fenster nicht mehr aktualisiert, man denkt, es passiert garnichts... 
Macht man dann einen Refresh des Fensters, ist das Objekt auf einmal da. 

Vorher hats funktioniert, seit dem neuen WebAdmin nicht mehr. Meine Versionen Admin 3.1.12 und Cloud 2.4.5
- und ja, ich hab den Cloud adapter sogar komplett geloescht, erst aus den Instanzen, dann aus IOBroker. Anschliessend system neu gebooted und den Adapter von Github per Link installiert. 
Geholfen hats nicht, effekt war vorher der gleiche.

Achso, vielleicht nicht unwichtig: ich kann SWITCHs adden, aber keine Buttons! Das ging vorher. 
Alle mit Broadlink angelegten IR-Codes sind Buttons...  die haette ich gerne wieder drin.. :-)

Vorher ging nach dem Auswaehlen eines Objekts ja noch ein Fenster auf, wo man den Namen aendern kann, das kommt nicht mehr... ist hier der Hund begraben????

Gruss :-)

**Comment by Toby1337** [comment]
Geräte hinzufügen hat bei mir ebenfalls keine Funktion mehr. Die entsprechenden Adapter sind alle auf dem aktuellsten Stand.

Bitte um Hilfe.

Grüße
![image](https://user-images.githubusercontent.com/37037900/36944178-2bd71768-1f97-11e8-9ae2-2d4cc7cef08a.png)

**Comment by E812** [comment]
Bei mir das gleiche wie bei Toby1337. Habe gestern Version 2.4.6 des cloud-Adapters eingespielt, nachdem die Alexa-Steuerung nicht mehr möglich war, und der alte cloud-Adapter im Log ausgab, dass die Anmeldung nicht möglich sei, da minimal Version 2.4.6 erforderlich wäre.

**Comment by Toby1337** [comment]
Ich habe soeben den Adapter neu installiert und auf Version 2.4.7 aktualisiert. Leider ohne Erfolg. Laut Changelog wurde der Bug allerdings seit Version 2.4.6 behoben. 

Ich denke es gibt noch ein weiteres Problem.

Was etwas komisch ist, dass mein Admin oben Rechts Version 2.0.9 anzeigt. Allerdings wird bei dem Adapter selbst die Version 3.2.3 angezeigt. Kann es trotzdem damit was zu tun haben?

Grüße

**Comment by E812** [comment]
Bei mir stand auch noch oben rechts die Version 2.0.9. Ich habe zunächst versucht, den Adapter upzugraden, hat aber nicht geklappt. Ich habe dann den admin Adapter über dnen Befehl iobroker del admin gelöscht und über iobroker add admin wieder hinzugefügt. In der Ausgabe erschien nach der Zeile
npm install iobroker.admin --production --prefix "/opt/iobroker" (System call)
anscheinend ein Fehler:
npm ERR! code 1
Keine Ahnung, was das zu bedeuten hat, aber die Installation ging trotzdem weiter.
Ich konnte den Adapter anschließend mit iobroker start admin erfolgreich starten und jetzt erscheint in der Ecke oben rechts die Version 3.3.1.
Gebracht hat das aber nichts, ich kann trotzdem keine Smart-Devices anlegen. Das Fehlerbild ist das gleiche, wie zuvor.

**Comment by GermanBluefox** [comment]
Admin 3.3.5, Cloud 2.5.0?
Wenn nicht dann bitte updaten.
Dann bitte unterscheiden ob Dialog aufgemacht wird und das Anlegen wird abgelehnt. Oder ob Dialog gar nicht aufgemacht wird.
1. Dialog geht: dann versucht ihr das Gerät anzulegen, was nicht steuerbar ist oder role
