### ISSUE TITLE
Cloud 2.4.4. 2.4.5 in Windows 10 ioBroker buggy

### ISSUE THREAD

**Issue by elzershark** [ioBroker/ioBroker.cloud#63]
Windows 10. iobroker.
https://youtu.be/aPTvQpnEQVE
Umlaute setzen alle Geräte offline. Keine Geräte funktionieren mehr.
iobroker kann komplett nicht verwendet werden.
Das ist bei der cloud 2.4.4... 2.4.5.
Alle Versionen davor funktionieren mit Umlauten.
Die Zeichenkodierung ist buggy in der Cloud

**Comment by pfleiderer** [comment]
Kann ich nicht betätigen. Mein Smartname "Küche Licht" wird erkannt und problemlos geschaltet.
admin 3.1.12
cloud 2.4.5

**Comment by elzershark** [comment]
Dann hast Du nicht ioBroker über Windows laufen

**Comment by pfleiderer** [comment]
Das stimmt allerdings. Läuft auf einem Raspi unter Linux. Sorry habe ich nicht enau genug gelesen.

**Comment by WolfspiritM** [comment]
This also happens on Linux aswell and is not only related to Window. The reason why this is happening is that Alexa expects the applianceId to not contain anything besides letters and numbers. Recent change of the regex however introduced umlauts which makes alexa ignore the whole discovery response. I removed umlauts again but left Cyrillic ones in in my pull request. I tried to change the FriendlyName to cyrillic to test but it seems there is a block for friendlyName containing cyrillic characters anyway somewhere before that part.

I have no idea if alexa allows cyrillic in there...that needs to be tested but I assume they also count as invalid characters.

We might have a problem if the friendlyName only contains cyrillic characters then as it will end in an empty friendlyName.

Does Alexa support cyrillic at all?

**Comment by werner256** [comment]
Danke für die ausführliche Analyse! Da es ja bisher (und mit cloud 2.1.1 noch immer) auch mit Umaluten funktioniert - wird es dann auch irgendwann wieder funktionieren?

**Comment by WolfspiritM** [comment]
Ja klar.
Bisher wurde für die ID (nicht den Namen) Umlaute weggeschnitten.
Daher hat es funktioniert :-) Nach meiner Änderung ist das auch wieder genauso.
Ich schätze mit 2.4.6 wird es wieder gehen.

**Comment by djalexz** [comment]
Tatsache, habe die Daten wie von WolfspiritM beschrieben manuell in den Dateien des Cloud Adapters geändert und ihn neugestartet.
Rolllade in der Küche funktioniert wieder :-)

Klasse Arbeit, vielen Dank.
Ich denke, dass BlueFox das bald mergen wird.

**Comment by AlCalzone** [comment]
> We might have a problem if the friendlyName only contains cyrillic characters then as it will end in an empty friendlyName.
> 
> Does Alexa support cyrillic at all?

Maybe this helps, could also work for german umlauts:
https://www.npmjs.com/package/unidecode
