### ISSUE TITLE
Mozilla Firefox - Liste der Smart Geräte nicht scrollbar

### ISSUE THREAD

**Issue by mesche** [ioBroker/ioBroker.cloud#66]
Die Liste der Smart Geräte kann im Mozilla Firefox nicht gescrollt werden.

ioBroker.admin 3.1.12
ioBroker.cloud 2.4.5
Mozilla Firefox 58.0.1 (64-Bit) Mac/Windows

**Comment by eumats** [comment]
Gleiches verhalten bei Safari
admin: 3.2.0
cloud: 2.4.6

**Comment by GermanBluefox** [comment]
admin 3.3.1
Cloud 2.4.6
![image](https://user-images.githubusercontent.com/4582016/37258014-86bead8c-2571-11e8-8009-21c9687a8fb4.png)
