### ISSUE TITLE
No Devices at amazon Alexa / no connection

### ISSUE THREAD

**Issue by DavidPasch** [ioBroker/ioBroker.cloud#67]
Seit einigen Tagen funktioniert die Sprachteuerung nicht - Connection alles richig und grün. Mal alle Devices bei Alexa gelöscht - Suche - nichts gefunden.
IOBroker restart - keine Besserung.

Funktionierte seit nem 3/4 Jahr alles Problemlos. Seit Admin 3 Umstellung sehr buggy bzw. aktuell geht gar nix mehr.

**Comment by pfleiderer** [comment]
Ich hatte das selbe Problem. Mittlerweile läüft aber wieder alles. 
Iobroker auf raspi
admin 3.1.12
cloud 2.4.5
was ich gemacht habe

cloud instanz gelöscht
cloud adapter gelöscht
admin instanz gelöscht
admin adater gelöscht
admin neu istalliert (über terminal)
cloud adapter neu instlliert 2.4.4
update cloud auf 2.4.5
von iobroker skill abmelden und neu anmelden

... so hat es bei mir geklappt und ich kann über alexa steuern und auch neue objekte im cloud adapter anlegen.

viel Glück

**Comment by DavidPasch** [comment]
Na aber Admin und Cloud Adapter komplett zu killen kann ja nun auch nicht die Lösung sein. Gerade im Cloud Adapter hab ich einiges selbst definiert - die erneute Arbeit würd' ich mir eigentlich ersparen wollen.

**Comment by DavidPasch** [comment]
Also ...

Downgrade auf 2.4.4, Skill deaktiviert, aktiviert, Geräte suchen lassen - läuft.
Upgrade auf 2.4.5 - alles offline. Skill deaktiviert, aktiviert, neu Suche - keine Geräte.

2.4.5 scheint allgemein ein Problem zu haben, bleibe auf 2.4.4 bis es eine > 2.4.5 gibt.

**Comment by SidOmsa** [comment]
Hi,

hatte auch das Problem.
Seit Downgrade auf 2.4.4. geht es wieder. Danke für den Tipp

**Comment by Elchbier** [comment]
Hi, 
ich hab das selbe Problem. 2.4.4. läuft ohne Probleme, nur sobald man auf + drückt wird der Bildschirm grau und nichts passiert mehr und man kann keine Geräte hinzufügen.
Bei Version 2.4.5 und auch 2.4.6 kann ich über Alexa keine Geräte mehr steuern und nach neuen Geräten suchen funktioniert auch nicht.
 Es kommt dann die Meldung ioBroker reagiert nicht.

**Comment by WolfspiritM** [comment]
@Elchbier Sicher, dass es mit 2.4.6 nicht gelöst ist? Mit 2.4.6 sollten neue geräte zumindest wieder erkannt werden. Dann über https://alexa.amazon.de alle doppelten und alten (Offline) geräte löschen und nochmal das schalten probieren. Dann sollte es funktionieren.

**Comment by pfleiderer** [comment]
2.4.6 funktioniert einwandfrei. Wie @WolfspiritM  geschrieben ht, die nach dem einlesen in die Alexa app als (offline) angegebenen Geräte in der app entfernen, oder alles löschen und neu einlesen.
Eventuell  mal versuchen die Verbindung zum iobrokr skill zu entfernen und neu zu verbinden

**Comment by Elchbier** [comment]
Ich hab nochmal nach neuen Geräten gesucht. Und dann die alten gelöscht. Jetzt geht alles, danke. Fehler kann geschlossen werden!!
