### ISSUE TITLE
run scripts via Alexa

### ISSUE THREAD

**Issue by sometimestoday** [ioBroker/ioBroker.cloud#69]
Es ist leider nicht mehr möglich Skripte über Alexa zu starten - diese erscheinen nicht  unter "Smart Geräte"

**Comment by Baenker** [comment]
Das kann ich bei mir nicht nachvollziehen. Sowohl mit Version 2.4.4 als auch mit der 2.4.6 sehe ich die Scripte aus iobroker in der Alexa App und kann diese auch starten...
