### ISSUE TITLE
Amazon Echo Connection lost after a while

### ISSUE THREAD

**Issue by RobertHerter** [ioBroker/ioBroker.cloud#7]
Echo marks the adapter as offline after a while. After restart of the adapter everything works fine
for a while. No error is logged.

**Comment by Apollon77** [comment]
In Instance overview of ioBroker? Is the dot in front of the cloud instance green or yellow when you have this problem?

**Comment by RobertHerter** [comment]
The dot in front of the instance is green. No Error logged.
But somtimes:
`cloud.0	2017-02-10 12:57:42.387	info	Connection changed: CONNECTED
cloud.0	2017-02-10 12:57:42.169	info	2017-02-10T11:57:42.168Z Connected system.user.admin
cloud.0	2017-02-10 12:57:32.143	info	Connection changed: DISCONNECTED
cloud.0	2017-02-10 12:57:32.141	info	Connection changed: DISCONNECTED
cloud.0	2017-02-10 12:57:32.138	error	Ping timeout
cloud.0	2017-02-10 12:56:57.121	info	Connection changed: CONNECTED
cloud.0	2017-02-10 12:56:56.899	info	2017-02-10T11:56:56.898Z Connected system.user.admin
cloud.0	2017-02-10 12:56:46.880	info	Connection changed: DISCONNECTED
cloud.0	2017-02-10 12:56:46.878	info	Connection changed: DISCONNECTED
cloud.0	2017-02-10 12:56:46.876	error	Ping timeout
cloud.0	2017-02-10 12:56:31.862	info	Connection changed: CONNECTED
cloud.0	2017-02-10 12:56:31.625	info	2017-02-10T11:56:31.624Z Connected system.user.admin
cloud.0	2017-02-10 12:56:21.598	info	Connection changed: DISCONNECTED
cloud.0	2017-02-10 12:56:21.595	info	Connection changed: DISCONNECTED
cloud.0	2017-02-10 12:56:21.591	error	Ping timeout
cloud.0	2017-02-10 12:56:06.585	info	Connection changed: CONNECTED
cloud.0	2017-02-10 12:56:06.291	info	2017-02-10T11:56:06.290Z Connected system.user.admin
cloud.0	2017-02-10 12:55:56.238	info	Connection changed: DISCONNECTED
cloud.0	2017-02-10 12:55:56.231	info	Connection changed: DISCONNECTED`

**Comment by kasperj** [comment]
Was fixed a while ago, didn't it?

**Comment by GermanBluefox** [comment]
It was fixedecided in April.

6 Июн 2017 г. 19:49 пользователь "Jan-Henrik Kasper" <
notifications@github.com> написал:
