### ISSUE TITLE
ifttt Link in der Cloud funktioniert nicht bei Pro

### ISSUE THREAD

**Issue by elzershark** [ioBroker/ioBroker.cloud#72]
http://forum.iobroker.net/viewtopic.php?f=22&t=11942

Der Link in der Cloud für IFTTT funktioniert nicht bei der Cloud Pro Version.
(Services und IFTTT...oben)
Bei Objekte- Cloud- -ifttt wird kein Wert rein geschrieben

Admin 2.0.9 ,Cloud 2.4.4
Wenn ich Umstelle in Cloud normal geht es.

https://iobroker.net/ifttt/elzershark@y ... *****9176d "geht"
https://iobroker.net/ifttt/@pro_elzersh ... ****b605a4 "geht nicht"

Hab jetzt schon etliche Versionen Probiert. Noch nicht gefunden wo es geht.

Bei ifttt wird angezeigt "Unable to make web request. Your server returned a 502"

Spoiler: Show hidden text

Und der Link für ifttt wird in der Cloud nicht angezeigt. Admin 3.1.12, 3.2.0

**Comment by rooftopbbq** [comment]
Ersetze mal in der Pro Version das .net in der Domain durch .pro

**Comment by elzershark** [comment]
oh man.. manchmal sieht man den Wald vor lauter Bäumen nicht... funzt. txh :)
