### ISSUE TITLE
Smart Gerätetyp Rollladen

### ISSUE THREAD

**Issue by Blackei** [ioBroker/ioBroker.cloud#73]
Hi,
habe gesehen das es mittlerweile die Möglichkeit gibt den Typ der Smart Geräte zu definieren. Mir fehlt allerdings der Typ für Rollladen. Gibt es die Möglichkeit den Typ noch zu integrieren?

Danke

**Comment by WolfspiritM** [comment]
Hi,

Die angezeigten Typen sind alle welche Alexa (zumindest in dieser Skillversion) unterstützt.
Daher ist es nicht möglich hier weitere Typen hinzuzufügen.

**Comment by Baenker** [comment]
Sollte sich ebenfalls erledigt haben:

Die Gerätesteuerung über Alexa via Cloud-Adapter wurde ab 4.1.2020 eingestellt!

**Comment by Apollon77** [comment]
you're right. Thank you!
