### ISSUE TITLE
Zustand vom Smarthome Gerät werden in der Alexa App nicht angezeigt

### ISSUE THREAD

**Issue by Baenker** [ioBroker/ioBroker.cloud#75]
Ich weiß nicht ob das schon immer so war oder erst ab Version 2.4.6. Ich glaube in 2.4.4 war das noch anders...

Wenn ich über die Alexa App ein homematic Gerät (deklariert als Licht) einschlate sehe ich in der App den Zustand nicht? Eigentlich ist es egal womit das Licht eingeschaltet wurde. In der Alexa App wird der Zustand der Geräte die über iobroker an Alexa angebunden werden nicht.

Bei Lampen die über die hue-Brige an Alexa angebunden sind sieht man es ohne Probleme.

**Comment by Baenker** [comment]
Update: Auch beim Downgrade auf 2.4.4 werden die Zustände nicht korrekt angezeigt. Somit kann es nicht an der Version liegen.

Ich vermute es könnte an den Wartungsarbeiten bzw Optimierungen am Cloud-Server liegen? War es nicht so, dass es Probleme gab weil Geräte zuviele Zustände an den Server gesendet haben und er deswegen teilweise ausfiel? Könnte die Optimierung gewesen sein einfach die Zustände garnicht mehr zu melden?

**Comment by GermanBluefox** [comment]
Das ist nicht mal implementiert.
