### ISSUE TITLE
Error while connecting to cloud: Error: websocket error

### ISSUE THREAD

**Issue by Evil-Error** [ioBroker/ioBroker.cloud#77]
Problem came from one day to the next...after it works good and stable for about 3 weeks.
Used version is 2.4.7

What was done and did not solve the problem:

- host restarted
- adapter restarted (many times)
- un-installed the adapter
- re-installed the adapter (tried different versions)
- tried with a new api-key from iobroker.net
- also tried with another web instance 
- restarted my routers and switches...just 4 fun

I'm thankful for any hints or ideas to solve this problem permanently. 

(aus Gewohnheit in eng. Sprache)

**Comment by Kunibert-007** [comment]
Have the same problem (V2.4.6)

**Comment by GermanBluefox** [comment]
Please say the version of js-controller..

**Comment by Kunibert-007** [comment]
V1. 3.0

**Comment by GermanBluefox** [comment]
I must confess, that I with unityMedia have the problem to access from linux (not from windows) the site iobroker.net. And I do not understand WTF. What the provider do you have?

**Comment by Apollon77** [comment]
I also have unitymedia (in BW) and no problems

**Comment by Evil-Error** [comment]
I know something about the problem with UM - they have sometime problems with the DNS resolution for random sites - had the same issue in our company with some of our customers...

but my provider is a local one, INEXIO so I don't believe that is the root cause. 

 I'm new with io - can some one explain shortly were I find the js version (sorry)? console or GUI, equal.

**Comment by Evil-Error** [comment]
sry guys - was a really stupid question...

version is 1.2.3

**Comment by Evil-Error** [comment]
All-right - I could fix my problem with the cloud adapter.
The cause was strange and a system problem - **nothing with iobroker**!!

regarding the cause: I don't understand why, but my "resolv.conf" was damaged. 
I found it out by simply making a ping to "download.iobroker.net" --> the IP wasn't resolved correct.
I did not think about it earlier because all other stuff were working normal with IO.

Sorry for the trouble and thanks for your help! cheers.


For others which maybe have the same problem, under debian you will find resolv.conf under
"/etc/resolv.conf" 
Normally you should enter two nameserver's: 1st your router/firewall/gate,  2nd a DNS-Server of google e.q.
Should looks like that:

nameserver 192.168.178.1
nameserver 8.8.8.8
