### ISSUE TITLE
Hue stellt bei "Weiss" auf rot

### ISSUE THREAD

**Issue by nob0dy80** [ioBroker/ioBroker.cloud#78]
Hallo,

bei der Ansage "Stelle Lampe xyz auf weiss" wird die Lampe auf rot gestellt.
Getestet mit Lightstrip und Farb-E27 gen4.

Oliver.Schulze hatte schonmal einen Fix für die alte Cloudadapterversion gemacht in der Datei alexaSmartHomeV2 damit ging alles. Mit aktuellen Cloudadaptern funktioniert dieser Fix nicht mehr.

Die andere Farbanwahl klappt reibungslos; nur zurück von Farbe auf weiß endet immer in rot.

**Comment by Baenker** [comment]
Da man die Geräte nicht mehr über diesen Adapter steuern kann sollte sich das Problem erledigt haben? Somit sollte der Issue geschlossen werden.

**Comment by Apollon77** [comment]
you're right. Thank you!
