### ISSUE TITLE
Buttons lassen sich nicht als smartgeräte anlegen

### ISSUE THREAD

**Issue by Weimaraner28** [ioBroker/ioBroker.cloud#80]
https://forum.iobroker.net/viewtopic.php?f=20&t=12599

States vom Typ "buttons"  lassen sich nicht als smartgerät anlegen. Nach Auswahl des States und bestätigen schließt sich der Dialog, aber es öffnet sich weder das nächste Dialogfenster noch legt sich irgendein Gerät an.

**Comment by GermanBluefox** [comment]
Works as designed. I am thinking about changing it.
