### ISSUE TITLE
White List für Services

### ISSUE THREAD

**Issue by Psens666** [ioBroker/ioBroker.cloud#82]
Hallo, irgendwie komme ich nicht weiter, ich kann keinen Custom Service anlegen. wenn ich einen Namen eingebe bleiben die Felder Speichern und Speichern und Schließen grau. kann mir jemand weiter helfen? bzw. was mache ich falsch?

**Comment by GermanBluefox** [comment]
Enter im Feld drücken?

**Comment by Psens666** [comment]
Dankeschön, manchmal kann es so leicht sein!
