### ISSUE TITLE
Hinzufügen von Smartgeräten (Nach der Auswahl im Dialog keine Reaktion)

### ISSUE THREAD

**Issue by Toby1337** [ioBroker/ioBroker.cloud#83]
Hallo,

ich habe/hatte das Problem, dass die Funktion "Geräte hinzufügen" scheinbar nicht funktioniert hatte.
Von den Versionen her bin ich auf dem neusten Stand (Admin 3.3.0 und Cloud 2.5.0).

Ablauf
Der Auswahl-Objekt-Dialog geht auf, ich wähle ein Objekt aus 
-> Keine Reaktion

Bisher dachte ich, dass es sich hierbei um einen Bug handelte, da ich in der vorherigen Version keine Probleme hatte.

Nachdem ich mir den Quellcode angeschaut habe, habe ich festgestellt, dass ein Objekt lediglich hinzugefügt wird, wenn eine Rolle eingetragen ist:

![image](https://user-images.githubusercontent.com/37037900/38263922-c5b0aeac-3771-11e8-8cf0-ddab313f9329.png)

Mit diesem Wissen, kann ich mir nun selbst helfen.
Allerdings stellt sich für mich die Frage: **Weshalb wird eine Rolle zwangsläufig vorausgesetzt?**
Nicht dass ich im nächsten Update wieder alles zerschieße..

**Anregung**:
Es werden in dieser Funktion ja einige Bedingungen abgefragt. Mir ist bewusst, dass es eine Frage der Zeit und Motivation ist :)
Allerdings wäre eine Meldung, dass das ausgewählte Objekt nicht den Voraussetzungen für ein Smartgerät entsprechen sehr hilfreich. Dann gibt es sicherlich weniger Bugreports bezüglich dieser Funktion.
Ohne Meldung war ich der Meinung, dass die Funktion einfach nur kaputt ist.

Viele Grüße und Danke auf die Reaktion vom letzten Issue

**Comment by Toby1337** [comment]
Als Info:
![image](https://user-images.githubusercontent.com/37037900/38265129-3dcf5688-3775-11e8-87c0-b327a6ec03ee.png)
Ich benutze beispielsweise folgendes Objekt um mein Esszimmerlicht zu verwalten. Das Licht funktioniert per Funk und kann entweder über mein broadlink oder über den normalen Lichtschalter an und ausgeschaltet werden.
Daher kriege ich es leider nicht hin den Zustand richtig zu verwalten, weshalb ich etwas "hacken" muss.

Kriege ich in Zukunft damit Probleme?

**Comment by GermanBluefox** [comment]
>Kriege ich in Zukunft damit Probleme?

Rolle "Licht" gibt es nicht. "Licht" ist die Funktion. Du solltest "level.dimmer" verwenden.

**Comment by GermanBluefox** [comment]
>Weshalb wird eine Rolle zwangsläufig vorausgesetzt?

Mit rolle wird es erkannt wie man das Objekt behandeln muss. Ob das Switch, Dimmer oder Blind ist.

**Comment by overfl0w72** [comment]
Hi, habe das gleiche Problem, bin quasi totaler Anfänger und weiß mir nicht so richtig zu helfen, welche Rolle soll ich dem Objekt geben? Danke im Voraus :)
