### ISSUE TITLE
Mehrere Cloud Anbindungen (cloud Instanzen ermöglichen)

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.cloud#85]
Siehe [https://forum.iobroker.net/viewtopic.php?f=8&t=7959#p93522](https://forum.iobroker.net/viewtopic.php?f=8&t=7959#p93522)

Mehrfacher Wunsch die Cloud-Instanz ein zweites Mal installieren zu können, um z.B. zwei Amazon-Anbindungen vornehmen zu können.

**Comment by GermanBluefox** [comment]
Meine Installation ist mit .pro und mit .net Verbunden. Wo ist das Problem?

**Comment by GermanBluefox** [comment]
Da hast du recht..

2018-04-21 9:22 GMT+02:00 klaus-schuster <notifications@github.com>:
