### ISSUE TITLE
Cloud adapter crashes when text2command does not respond

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.cloud#86]
In this line
https://github.com/ioBroker/ioBroker.cloud/blob/6cb6f9a5c9660937e534e9fd6464990fbca32750/lib/alexaCustom.js#L43
`request.request.intent.slots.device` is `undefined` when called from
https://github.com/ioBroker/ioBroker.cloud/blob/6cb6f9a5c9660937e534e9fd6464990fbca32750/lib/alexaCustom.js#L159

Not sure how the adapter should respond in that case.

**Comment by GermanBluefox** [comment]
Close?

2018-05-05 9:31 GMT+02:00 AlCalzone <notifications@github.com>:
