### ISSUE TITLE
Javascript Adapter über Cloud Admin rot, obwohl kein Problem vorliegt

### ISSUE THREAD

**Issue by MarkSau** [ioBroker/ioBroker.cloud#89]
Der Javascript Adapter wird über den Cloud Admin rot angezeigt. Im Gegensatz zur "Heimansicht". Hier allerdings auch im Admin 3 Interface. Dort ist er grün. Das verwirrt etwas, wenn man von draussen drauf schaut. Auch weil manchmal der Javascript Adapter tatsächlich ein Problem hat.
![image](https://user-images.githubusercontent.com/22911084/40222390-9eafd496-5a7f-11e8-84e4-30cc7a2fe256.png)

![image](https://user-images.githubusercontent.com/22911084/40222420-b3fdbaa2-5a7f-11e8-80ba-794b940590c1.png)

Installierte Version:
Cloud 2.6.1
Admin 3.4.3
JS.Controller 1.4.2
Script Engine 3.6.4
NPM 6.0.1
Node 8.11.2
NodeJS 8.11.2

**Comment by Apollon77** [comment]
Auf cloud ist immer noch ein 2er Admin, korrekt? Dannist der Fehler bekannt und wird gefrixt sobald Admin3 auf Cloud ist

**Comment by Baenker** [comment]
Admin3 ist auf Cloud verfügbar! Sollte damit nicht der Fehler hier geschlossen werden?

**Comment by Apollon77** [comment]
you're right. Thank you!
