### ISSUE TITLE
Routine mit vielen Geräten funktioniert nicht

### ISSUE THREAD

**Issue by petkoh85** [ioBroker/ioBroker.cloud#90]
Hallo,
ich nutze eine Routine, wenn ich ins Bett gehe. Dabei wird eine Lampe an und ca. 15 Lampen aus geschaltet. Wenn ich die Routine starte, funktioniert sie nicht und im Log erscheint die Fehlermeldung "Cloud says: too many state updates" und die Cloud ist für fünf Minuten gesperrt. Gibt es eine Möglichkeit diesen Fehler zu beheben? (Wenn es einer ist) Oder gibt es eine Möglichkeit diese Überwachung zu ändern?
Viele Grüße

**Comment by Apollon77** [comment]
Im ersten Schritt ist das kein fehler sondern ein Schutzmechanismus des cloudservers. 

Müssen wir uns ansehen.  

Eine Variante wäre ein „virtuelles Gerät“ z.b. als JavaScript State der dann die Routine quasi ersetzt aber nur als ein state von außen geschaltet wird.
