### ISSUE TITLE
Error text2command

### ISSUE THREAD

**Issue by StainDN** [ioBroker/ioBroker.cloud#91]
Version 2.6.1 in C:/ioBroker/node_modules/iobroker.cloud, node: v8.11.1

send POST https://iobroker.net/service/text2command/key

log:

host.DEMON | 2018-06-18 07:04:01.939 | error | instance system.adapter.cloud.0 terminated with code 0 (OK)
-- | -- | -- | --
host.DEMON | 2018-06-18 07:04:01.939 | error | Caught by controller[0]: at Decoder.add (C:\ioBroker\node_modules\iobroker.cloud\node_modules\socket.io-client\node_modules\socket.io-parser\index.js:251:12)
host.DEMON | 2018-06-18 07:04:01.939 | error | Caught by controller[0]: at Decoder.Emitter.emit (C:\ioBroker\node_modules\iobroker.cloud\node_modules\socket.io-client\node_modules\component-emitter\index.js:133:20)
host.DEMON | 2018-06-18 07:04:01.939 | error | Caught by controller[0]: at Decoder. (C:\ioBroker\node_modules\iobroker.cloud\node_modules\socket.io-client\node_modules\component-bind\index.js:21:15)
host.DEMON | 2018-06-18 07:04:01.939 | error | Caught by controller[0]: at Manager.ondecoded (C:\ioBroker\node_modules\iobroker.cloud\node_modules\socket.io-client\lib\manager.js:345:8)
host.DEMON | 2018-06-18 07:04:01.939 | error | Caught by controller[0]: at Manager.Emitter.emit (C:\ioBroker\node_modules\iobroker.cloud\node_modules\socket.io-client\node_modules\component-emitter\index.js:133:20)
host.DEMON | 2018-06-18 07:04:01.939 | error | Caught by controller[0]: at Manager. (C:\ioBroker\node_modules\iobroker.cloud\node_modules\socket.io-client\node_modules\component-bind\index.js:21:15)
host.DEMON | 2018-06-18 07:04:01.939 | error | Caught by controller[0]: at Socket.onpacket (C:\ioBroker\node_modules\iobroker.cloud\node_modules\socket.io-client\lib\socket.js:236:12)
host.DEMON | 2018-06-18 07:04:01.939 | error | Caught by controller[0]: at Socket.onevent (C:\ioBroker\node_modules\iobroker.cloud\node_modules\socket.io-client\lib\socket.js:278:10)
host.DEMON | 2018-06-18 07:04:01.939 | error | Caught by controller[0]: at Socket.Emitter.emit (C:\ioBroker\node_modules\iobroker.cloud\node_modules\socket.io-client\node_modules\component-emitter\index.js:133:20)
host.DEMON | 2018-06-18 07:04:01.939 | error | Caught by controller[0]: at Socket. (C:\ioBroker\node_modules\iobroker.cloud\main.js:683:33)
host.DEMON | 2018-06-18 07:04:01.938 | error | Caught by controller[0]: TypeError: adapter.setForeginState is not a function

**Comment by Apollon77** [comment]
Fixed in Github-Version
