### ISSUE TITLE
Webpage for displaying the health of the iobroker cloud system

### ISSUE THREAD

**Issue by Stabilostick** [ioBroker/ioBroker.cloud#92]
I suggest to introduce a self-updating status page for the cloud connectivity. Something like http://status.sunny-operations.de/ with less overhead.

The status page can then be used as an information source, e.g. when the questions pile up again in the forum. Furthermore, the cloud adapter could use the additional information and just tell us why it does not do what it is supposed to do.

And there is the possibility to display automatic maintenance informationen for the clients.

**Comment by stabilostick** [comment]
See https://forum.iobroker.net/viewtopic.php?f=23&t=15388
