### ISSUE TITLE
Services und IFTTT - White list für Services

### ISSUE THREAD

**Issue by dslraser** [ioBroker/ioBroker.cloud#93]
Wenn ich unter White List für Services etwas eintrage sollte doch ein entsprechendes Objekt angelegt werden, oder ? Hintergrund, ich habe den Places Adapter installiert und bin nach Anleitung vorgegangen, aber leider finde ich im Cloud Adapter kein erstelltes Objekt bzw. keinen Eintrag in den Objekten ?
Es ist bei beiden Cloud-Adaptern so, egal ob free oder pro.

**Comment by Apollon77** [comment]
Der State wird erst angelegten auch werte kommen. Eintrag im Admin ist nur whitelist das Daten falls sie kommen durchgelassen werden. 

Also bitte mal Daten korrekt senden. 

Wichtig: whitelist Angabe ist OHNE custom_ !! Nur das danach.

**Comment by dslraser** [comment]
Ich kriege keine Daten durch....
In der Handy App steht Fehler Endpoint state und darunter Response 502 Endpoint state message.
Woher weiss die Handy App wohin die Daten gehen, also zu welchem ioBroker Host ? Der Link über die White List kann doch mehrfach vorkommen. In dem Link steht doch kein Benutzer https://iobroker.pro/service/xyz/  ??? Ich verstehe das nicht so ganz.

**Comment by Apollon77** [comment]
Dann ist der Link falsch. Da muss deine Cloud is mit rein. Glaube nach dem domainnamen als erstem pfadbestandteil. Müsste aber im Cloud konfig im Admin angezeigt werden bzw auch in der GitHub readme zu Cloud Adapter gezeigt sein.

**Comment by dslraser** [comment]
ich habe jetzt alle möglichen Kombinationen im Link durch. (mit @ dazwischen oder : oder / den Cloudkey davor und dahinter) funktioniert alles nicht, die App meldet immer einen Fehler und kommt nicht durch.
In etwa so habe ich es probiert
https://iobroker.pro/services/standort/@pro_key
oder
https://iobroker.pro/@pro_key/services/standort/
oder
https://iobroker.pro:@pro_key/services/standort/
oder
https://iobroker.pro/services/standort:@pro_key
oder
https://iobroker.pro/services/standort@@pro_key
usw.usw.usw

Im Cloud Adapter habe ich custom und standort eingetragen (habe es auch mit "*" oder nur mit * probiert. 
Nun weiß ich auch nicht mehr weiter.
In der Cloud Konfig im Admin wird (Benutze folgende Link für einen eigenen Service)  sowie https://iobroker.net/service/     angezeigt, das stimmt ja sicher nicht, steht bei IFTTT auch falsch.

In der GitHub readme zum Cloud Adapter steht:
Services
There is a possibility to send messages to cloud adapter. If you call [POST]https://iobroker.net/service/custom_<NAME>/<user-app-key> und value as payload.

curl --data "myString" https://iobroker.net/service/custom_test/<user-app-key>
If you set in the settings the field "White list for services" the name custom_test, and call with "custom_test" as the service name, the state cloud.0.services.custom_test will be set to myString.

You may write "*" in white list and all services will be allowed.

Geht irgendwie alles nicht.

**Comment by Apollon77** [comment]
Also laut Doku muss es 

https://iobroker.net/service/custom_standort/@problubbbla

Sein wenn dein custom Datenfeld „standort“ sein Solleinnahmen so gewhitelistet ist

**Comment by dslraser** [comment]
ja, laut Doku....und warum .net, ist doch eine pro cloud, also .pro , oder ?
Geht aber trotzdem nicht.

**Comment by Apollon77** [comment]
Wenn pro dann .pro Jupp

**Comment by Apollon77** [comment]
Also Fakt ist bei mir geht:

https://iobroker.pro/service/custom_geofency_device0/@pro_ingo@email-und-so

Für „geofency_device0“ problemlos seit ewigkeiten.

**Comment by dslraser** [comment]
ich probiere es morgen weiter, muss ja irgendwie gehen, oder die App macht "Mist"---keine Ahnung.

**Comment by Apollon77** [comment]
Dann Versuchs mal per curl oder Browser. Dann siehst du ob der Link an sich tut.

**Comment by dslraser** [comment]
Moin, ich habe nun die Verbindung über folgenden Link hinbekommen:
https://iobroker.pro/service/custom_standort/@problablablub/
(wobei ich bei White list custom und als zweites Wort standort habe)
Die Adresse steht übrigens doch im Admin, aber nur wenn man sich über https://iobroker.pro anmeldet.
(lokal im Admin 3.4.9) steht die Adresse nicht.

**Comment by Apollon77** [comment]
Wenn du einen Vorschlag hast wie man die Doku dazu verbessern kann mach Vorschlag.
