### ISSUE TITLE
Import- und Exportfunktion für Smart-Geräte

### ISSUE THREAD

**Issue by ND72** [ioBroker/ioBroker.cloud#94]
Eine Import- und Exportfunktion für Smart-Geräte wäre klasse. Insbesondere wenn man das System neu aufgesetzt hat und kein komplettes Backup einspielen will würde das eine Menge Handarbeit sparen.

Vielen Dank und schöne Grüße.

**Comment by GermanBluefox** [comment]
Please move it to iot now. Cloud will not support devices from 01.03.2021
