### ISSUE TITLE
Sonos Playbar TV Eingeng

### ISSUE THREAD

**Issue by Don1971** [ioBroker/ioBroker.cloud#95]
Leider habe ich auf meiner Sonos Playbar keinen Zugriff auf den TV Eingang um ihn per Skript anzusprechen.
Alle anderen Einstellungen sind da.

**Comment by GermanBluefox** [comment]
Was hat das Mit der cloud zu tun?

вт, 14 авг. 2018 г., 10:31 Don1971 <notifications@github.com>:

**Comment by Baenker** [comment]
Kann aus meiner Sicht geschlossen werden. Problem hat nicht mit Cloud-Adapter zu tun.

**Comment by Apollon77** [comment]
you're right. Thank you!
