### ISSUE TITLE
Update Alexa SmartHome-Skill to "v3"

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.cloud#96]
actions -> capabilities:

https://developer.amazon.com/de/docs/smarthome/smart-home-skill-migration-guide.html

**Comment by GermanBluefox** [comment]
I even started the developing, but sow that it is a huge task: https://github.com/ioBroker/ioBroker.cloud/blob/master/lib/alexaSmartHomeV3.js

**Comment by Apollon77** [comment]
Yes very huge :-)

**Comment by Apollon77** [comment]
superceeded by https://github.com/ioBroker/ioBroker.iot/issues/29
