### ISSUE TITLE
2 Cloud Instanzen - gleiche Smartgeräte

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.cloud#97]
Hi,
ich habe im Haus 2 Amazon Accounts und möchte die Smartgeräte trennen, leider habe ich in beiden immer alle - was nervt, da ich im einem Account ca. 80 Geräte habe, und im anderen nur 10.
Habe zwar in der App des kleinen Accounts jetzt alle Geräte, die da nicht benutzt werden dürfen, deaktiviert, aber wenn derjenige schlau ist, dann kann er bei mir alles ein und ausschalten..

Ist es geplant, da eine Trennung zu ermöglichen?
Neue Smartgeräte können ja in beiden Instanzen automatisch angelegt werden, aber man sollte sie getrennt löschen dürfen.

**Comment by klaus-schuster** [comment]
siehe issue #85

**Comment by Ilovegym66** [comment]
double, see #85
