### ISSUE TITLE
MQTT via Cloud Adapter

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.cloud#98]
Please look into accessing your iobroker.pro instance via mqtt clients from the internet.

https://forum.iobroker.net/viewtopic.php?p=174961&sid=b076f675b53d518a40197c441d50a529#p174961

**Comment by DutchmanNL** [comment]
+1

User case :
Several iobroker installations in different Locationspeed to Share Data Witz wach Other.
IT would je great If The Cloud Services can bei usedas Public mqtt Server to Receiver Messages by MQTT Outsider of Thrones Home Network.

Equal to ifttt also for Other scenarios (device / Service Outsider the Home Network) thus Feature would add value of Thrones current Providers Cloud service
