### ISSUE TITLE
Möglichkeit für das Entfernen von vielen Geräten

### ISSUE THREAD

**Issue by derrapf** [ioBroker/ioBroker.cloud#99]
Aktuell kann man nur ein Gerät enfernen wenn man auf das Mülleimer Symbol drückt.
Dann öfnet sich eine Dialogbox und man muss nochmal bestätigen.

Das ist bei sehr vielen Geräten extrem lästig.
Besser wäre wenn man die Geräte über Checkboxen anhaken- und dann über ein globales Mülleimersymbol wegwerfen könnte.

Abgesehen davon verfärbt sich bei mir die Zeile nach dem Drücken des Mülleimers nur rot, das Gerät wird aber nicht gelöscht.  

Auch der "Speichern" Knopf bleibt ausgegraut wenn ich etwas ändere (auch in den Optionen). Ich kann den Dialog nur durch "Schliessen" verlassen.
Ist das ein Bug?

Gruss Ralf

**Comment by Baenker** [comment]
Kann das nicht geschlossen werden?

Die Gerätesteuerung über Alexa via Cloud-Adapter wurde ab 4.1.2020 eingestellt!

**Comment by Apollon77** [comment]
you're right. Thank you!

**Comment by derrapf** [comment]
Gilt auch für IOT

**Comment by Baenker** [comment]
@derrapf Dann sollte die Idee (ist ja kein Fehler) auch bei dem Adapter eingestellt werden.
